/*
Lichess.org API reference

Testing FIDEAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package lichess

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/atye/golichess"
)

func Test_lichess_FIDEAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FIDEAPIService FidePlayerGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var playerId int32

		resp, httpRes, err := apiClient.FIDEAPI.FidePlayerGet(context.Background(), playerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FIDEAPIService FidePlayerRatings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var playerId int32

		resp, httpRes, err := apiClient.FIDEAPI.FidePlayerRatings(context.Background(), playerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FIDEAPIService FidePlayerSearch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FIDEAPI.FidePlayerSearch(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
