/*
Lichess.org API reference

Testing ChallengesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_client_ChallengesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ChallengesAPIService AdminChallengeTokens", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChallengesAPI.AdminChallengeTokens(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChallengesAPIService ChallengeAccept", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var challengeId string

		resp, httpRes, err := apiClient.ChallengesAPI.ChallengeAccept(context.Background(), challengeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChallengesAPIService ChallengeAi", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChallengesAPI.ChallengeAi(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChallengesAPIService ChallengeCancel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var challengeId string

		resp, httpRes, err := apiClient.ChallengesAPI.ChallengeCancel(context.Background(), challengeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChallengesAPIService ChallengeCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var username string

		resp, httpRes, err := apiClient.ChallengesAPI.ChallengeCreate(context.Background(), username).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChallengesAPIService ChallengeDecline", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var challengeId string

		resp, httpRes, err := apiClient.ChallengesAPI.ChallengeDecline(context.Background(), challengeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChallengesAPIService ChallengeList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChallengesAPI.ChallengeList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChallengesAPIService ChallengeOpen", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChallengesAPI.ChallengeOpen(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChallengesAPIService ChallengeShow", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var challengeId string

		resp, httpRes, err := apiClient.ChallengesAPI.ChallengeShow(context.Background(), challengeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChallengesAPIService ChallengeStartClocks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gameId string

		resp, httpRes, err := apiClient.ChallengesAPI.ChallengeStartClocks(context.Background(), gameId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChallengesAPIService RoundAddTime", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gameId string
		var seconds int32

		resp, httpRes, err := apiClient.ChallengesAPI.RoundAddTime(context.Background(), gameId, seconds).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
