/*
Lichess.org API reference

Testing BroadcastsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package lichess

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/atye/golichess"
)

func Test_lichess_BroadcastsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BroadcastsAPIService BroadcastAllRoundsPgn", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastTournamentId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastAllRoundsPgn(context.Background(), broadcastTournamentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastMyRoundsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastMyRoundsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastPlayerGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastTournamentId string
		var playerId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastPlayerGet(context.Background(), broadcastTournamentId, playerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastPlayersGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastTournamentId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastPlayersGet(context.Background(), broadcastTournamentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastPush", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastRoundId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastPush(context.Background(), broadcastRoundId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastRoundCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastTournamentId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastRoundCreate(context.Background(), broadcastTournamentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastRoundGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastTournamentSlug string
		var broadcastRoundSlug string
		var broadcastRoundId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastRoundGet(context.Background(), broadcastTournamentSlug, broadcastRoundSlug, broadcastRoundId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastRoundPgn", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastRoundId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastRoundPgn(context.Background(), broadcastRoundId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastRoundReset", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastRoundId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastRoundReset(context.Background(), broadcastRoundId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastRoundUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastRoundId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastRoundUpdate(context.Background(), broadcastRoundId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastStreamRoundPgn", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastRoundId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastStreamRoundPgn(context.Background(), broadcastRoundId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastTeamLeaderboardGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastTournamentId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastTeamLeaderboardGet(context.Background(), broadcastTournamentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastTourCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastTourCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastTourGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastTournamentId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastTourGet(context.Background(), broadcastTournamentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastTourUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var broadcastTournamentId string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastTourUpdate(context.Background(), broadcastTournamentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastsByUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var username string

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastsByUser(context.Background(), username).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastsOfficial", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastsOfficial(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastsSearch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastsSearch(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BroadcastsAPIService BroadcastsTop", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BroadcastsAPI.BroadcastsTop(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
