// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package broadcast

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7 "github.com/atye/golichess/kiota/models"
)

// ItemPlayersRequestBuilder builds and executes requests for operations under \broadcast\{broadcastTournamentId}\players
type ItemPlayersRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ItemPlayersRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type ItemPlayersRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// ByPlayerId gets an item from the github.com/atye/golichess/kiota.broadcast.item.players.item collection
// returns a *ItemPlayersWithPlayerItemRequestBuilder when successful
func (m *ItemPlayersRequestBuilder) ByPlayerId(playerId string)(*ItemPlayersWithPlayerItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if playerId != "" {
        urlTplParams["playerId"] = playerId
    }
    return NewItemPlayersWithPlayerItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewItemPlayersRequestBuilderInternal instantiates a new ItemPlayersRequestBuilder and sets the default values.
func NewItemPlayersRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemPlayersRequestBuilder) {
    m := &ItemPlayersRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/broadcast/{broadcastTournamentId}/players", pathParameters),
    }
    return m
}
// NewItemPlayersRequestBuilder instantiates a new ItemPlayersRequestBuilder and sets the default values.
func NewItemPlayersRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemPlayersRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemPlayersRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get the list of players of a broadcast tournament, if available.
// returns a []BroadcastPlayerEntryable when successful
func (m *ItemPlayersRequestBuilder) Get(ctx context.Context, requestConfiguration *ItemPlayersRequestBuilderGetRequestConfiguration)([]i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.BroadcastPlayerEntryable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.CreateBroadcastPlayerEntryFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    val := make([]i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.BroadcastPlayerEntryable, len(res))
    for i, v := range res {
        if v != nil {
            val[i] = v.(i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.BroadcastPlayerEntryable)
        }
    }
    return val, nil
}
// ToGetRequestInformation get the list of players of a broadcast tournament, if available.
// returns a *RequestInformation when successful
func (m *ItemPlayersRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *ItemPlayersRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ItemPlayersRequestBuilder when successful
func (m *ItemPlayersRequestBuilder) WithUrl(rawUrl string)(*ItemPlayersRequestBuilder) {
    return NewItemPlayersRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
