// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package item

type GetDifficultyQueryParameterType int

const (
	EASIEST_GETDIFFICULTYQUERYPARAMETERTYPE GetDifficultyQueryParameterType = iota
	EASIER_GETDIFFICULTYQUERYPARAMETERTYPE
	NORMAL_GETDIFFICULTYQUERYPARAMETERTYPE
	HARDER_GETDIFFICULTYQUERYPARAMETERTYPE
	HARDEST_GETDIFFICULTYQUERYPARAMETERTYPE
)

func (i GetDifficultyQueryParameterType) String() string {
	return []string{"easiest", "easier", "normal", "harder", "hardest"}[i]
}

func ParseGetDifficultyQueryParameterType(v string) (any, error) {
	result := EASIEST_GETDIFFICULTYQUERYPARAMETERTYPE
	switch v {
	case "easiest":
		result = EASIEST_GETDIFFICULTYQUERYPARAMETERTYPE
	case "easier":
		result = EASIER_GETDIFFICULTYQUERYPARAMETERTYPE
	case "normal":
		result = NORMAL_GETDIFFICULTYQUERYPARAMETERTYPE
	case "harder":
		result = HARDER_GETDIFFICULTYQUERYPARAMETERTYPE
	case "hardest":
		result = HARDEST_GETDIFFICULTYQUERYPARAMETERTYPE
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeGetDifficultyQueryParameterType(values []GetDifficultyQueryParameterType) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i GetDifficultyQueryParameterType) isMultiValue() bool {
	return false
}
