// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package player

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7 "github.com/atye/golichess/kiota/models"
)

// PlayerRequestBuilder builds and executes requests for operations under \player
type PlayerRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// PlayerRequestBuilderGetQueryParameters **Endpoint: <https://explorer.lichess.org/player>**Games of a Lichess player.Responds with a stream of [newline delimited JSON](#description/streaming-with-nd-json). Will start indexingon demand, immediately respond with the current results, and streammore updates until indexing is complete. The stream is throttledand deduplicated. Empty lines may be sent to avoid timeouts.Will index new games at most once per minute, and revisit previouslyongoing games at most once every day.Example: `curl https://explorer.lichess.org/player?player=revoof&color=white&play=d2d4,d7d5&recentGames=1`
type PlayerRequestBuilderGetQueryParameters struct {
    // Look for games with *player* on the given side
    // Deprecated: This property is deprecated, use ColorAsGetColorQueryParameterType instead
    Color *string "uriparametername:\"color\""
    // Look for games with *player* on the given side
    ColorAsGetColorQueryParameterType *GetColorQueryParameterType "uriparametername:\"color\""
    // X-FEN of the root position
    Fen *string "uriparametername:\"fen\""
    // Comma separated list of modes
    // Deprecated: This property is deprecated, use ModesAsGetModesQueryParameterType instead
    Modes []string "uriparametername:\"modes\""
    // Comma separated list of modes
    ModesAsGetModesQueryParameterType []GetModesQueryParameterType "uriparametername:\"modes\""
    // Number of most common moves to display
    Moves *int32 "uriparametername:\"moves\""
    // Comma separated sequence of legal moves in UCI notation.Play additional moves starting from `fen`.Required to find an opening name, if `fen` is not an exact matchfor a named position.
    Play *string "uriparametername:\"play\""
    // Username or ID of the player
    Player *string "uriparametername:\"player\""
    // Number of recent games to display
    RecentGames *int32 "uriparametername:\"recentGames\""
    // Include only games from this month or later
    Since *string "uriparametername:\"since\""
    // Comma separated list of game speeds to look for
    // Deprecated: This property is deprecated, use SpeedsAsSpeed instead
    Speeds []string "uriparametername:\"speeds\""
    // Comma separated list of game speeds to look for
    SpeedsAsSpeed []i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.Speed "uriparametername:\"speeds\""
    // Include only games from this month or earlier
    Until *string "uriparametername:\"until\""
    // Variant
    // Deprecated: This property is deprecated, use VariantAsVariantKey instead
    Variant *string "uriparametername:\"variant\""
    // Variant
    VariantAsVariantKey *i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.VariantKey "uriparametername:\"variant\""
}
// PlayerRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type PlayerRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *PlayerRequestBuilderGetQueryParameters
}
// NewPlayerRequestBuilderInternal instantiates a new PlayerRequestBuilder and sets the default values.
func NewPlayerRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PlayerRequestBuilder) {
    m := &PlayerRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/player?color={color}&player={player}{&fen*,modes*,moves*,play*,recentGames*,since*,speeds*,until*,variant*}", pathParameters),
    }
    return m
}
// NewPlayerRequestBuilder instantiates a new PlayerRequestBuilder and sets the default values.
func NewPlayerRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PlayerRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewPlayerRequestBuilderInternal(urlParams, requestAdapter)
}
// Get **Endpoint: <https://explorer.lichess.org/player>**Games of a Lichess player.Responds with a stream of [newline delimited JSON](#description/streaming-with-nd-json). Will start indexingon demand, immediately respond with the current results, and streammore updates until indexing is complete. The stream is throttledand deduplicated. Empty lines may be sent to avoid timeouts.Will index new games at most once per minute, and revisit previouslyongoing games at most once every day.Example: `curl https://explorer.lichess.org/player?player=revoof&color=white&play=d2d4,d7d5&recentGames=1`
// returns a []byte when successful
func (m *PlayerRequestBuilder) Get(ctx context.Context, requestConfiguration *PlayerRequestBuilderGetRequestConfiguration)([]byte, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendPrimitive(ctx, requestInfo, "[]byte", nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.([]byte), nil
}
// ToGetRequestInformation **Endpoint: <https://explorer.lichess.org/player>**Games of a Lichess player.Responds with a stream of [newline delimited JSON](#description/streaming-with-nd-json). Will start indexingon demand, immediately respond with the current results, and streammore updates until indexing is complete. The stream is throttledand deduplicated. Empty lines may be sent to avoid timeouts.Will index new games at most once per minute, and revisit previouslyongoing games at most once every day.Example: `curl https://explorer.lichess.org/player?player=revoof&color=white&play=d2d4,d7d5&recentGames=1`
// returns a *RequestInformation when successful
func (m *PlayerRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *PlayerRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/x-ndjson")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *PlayerRequestBuilder when successful
func (m *PlayerRequestBuilder) WithUrl(rawUrl string)(*PlayerRequestBuilder) {
    return NewPlayerRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
