// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AccountPlayingGetResponse_nowPlaying_opponentMember1 struct {
	// The id property
	id *string
	// The rating property
	rating *int32
	// The ratingDiff property
	ratingDiff *int32
	// The username property
	username *string
}

// NewAccountPlayingGetResponse_nowPlaying_opponentMember1 instantiates a new AccountPlayingGetResponse_nowPlaying_opponentMember1 and sets the default values.
func NewAccountPlayingGetResponse_nowPlaying_opponentMember1() *AccountPlayingGetResponse_nowPlaying_opponentMember1 {
	m := &AccountPlayingGetResponse_nowPlaying_opponentMember1{}
	return m
}

// CreateAccountPlayingGetResponse_nowPlaying_opponentMember1FromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAccountPlayingGetResponse_nowPlaying_opponentMember1FromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewAccountPlayingGetResponse_nowPlaying_opponentMember1(), nil
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *AccountPlayingGetResponse_nowPlaying_opponentMember1) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["rating"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRating(val)
		}
		return nil
	}
	res["ratingDiff"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRatingDiff(val)
		}
		return nil
	}
	res["username"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUsername(val)
		}
		return nil
	}
	return res
}

// GetId gets the id property value. The id property
// returns a *string when successful
func (m *AccountPlayingGetResponse_nowPlaying_opponentMember1) GetId() *string {
	return m.id
}

// GetRating gets the rating property value. The rating property
// returns a *int32 when successful
func (m *AccountPlayingGetResponse_nowPlaying_opponentMember1) GetRating() *int32 {
	return m.rating
}

// GetRatingDiff gets the ratingDiff property value. The ratingDiff property
// returns a *int32 when successful
func (m *AccountPlayingGetResponse_nowPlaying_opponentMember1) GetRatingDiff() *int32 {
	return m.ratingDiff
}

// GetUsername gets the username property value. The username property
// returns a *string when successful
func (m *AccountPlayingGetResponse_nowPlaying_opponentMember1) GetUsername() *string {
	return m.username
}

// Serialize serializes information the current object
func (m *AccountPlayingGetResponse_nowPlaying_opponentMember1) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("id", m.GetId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("rating", m.GetRating())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("ratingDiff", m.GetRatingDiff())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("username", m.GetUsername())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetId sets the id property value. The id property
func (m *AccountPlayingGetResponse_nowPlaying_opponentMember1) SetId(value *string) {
	m.id = value
}

// SetRating sets the rating property value. The rating property
func (m *AccountPlayingGetResponse_nowPlaying_opponentMember1) SetRating(value *int32) {
	m.rating = value
}

// SetRatingDiff sets the ratingDiff property value. The ratingDiff property
func (m *AccountPlayingGetResponse_nowPlaying_opponentMember1) SetRatingDiff(value *int32) {
	m.ratingDiff = value
}

// SetUsername sets the username property value. The username property
func (m *AccountPlayingGetResponse_nowPlaying_opponentMember1) SetUsername(value *string) {
	m.username = value
}

type AccountPlayingGetResponse_nowPlaying_opponentMember1able interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetId() *string
	GetRating() *int32
	GetRatingDiff() *int32
	GetUsername() *string
	SetId(value *string)
	SetRating(value *int32)
	SetRatingDiff(value *int32)
	SetUsername(value *string)
}
