// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AccountEmailGetResponseable instead.
type AccountEmailResponse struct {
    AccountEmailGetResponse
}
// NewAccountEmailResponse instantiates a new AccountEmailResponse and sets the default values.
func NewAccountEmailResponse()(*AccountEmailResponse) {
    m := &AccountEmailResponse{
        AccountEmailGetResponse: *NewAccountEmailGetResponse(),
    }
    return m
}
// CreateAccountEmailResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAccountEmailResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAccountEmailResponse(), nil
}
// Deprecated: This class is obsolete. Use AccountEmailGetResponseable instead.
type AccountEmailResponseable interface {
    AccountEmailGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
