// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// PuzzleRequestBuilder builds and executes requests for operations under \api\puzzle
type PuzzleRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// Activity the activity property
// returns a *PuzzleActivityRequestBuilder when successful
func (m *PuzzleRequestBuilder) Activity()(*PuzzleActivityRequestBuilder) {
    return NewPuzzleActivityRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Batch the batch property
// returns a *PuzzleBatchRequestBuilder when successful
func (m *PuzzleRequestBuilder) Batch()(*PuzzleBatchRequestBuilder) {
    return NewPuzzleBatchRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ById gets an item from the github.com/atye/golichess/kiota.api.puzzle.item collection
// returns a *PuzzlePuzzleItemRequestBuilder when successful
func (m *PuzzleRequestBuilder) ById(id string)(*PuzzlePuzzleItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if id != "" {
        urlTplParams["id"] = id
    }
    return NewPuzzlePuzzleItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewPuzzleRequestBuilderInternal instantiates a new PuzzleRequestBuilder and sets the default values.
func NewPuzzleRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PuzzleRequestBuilder) {
    m := &PuzzleRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/puzzle", pathParameters),
    }
    return m
}
// NewPuzzleRequestBuilder instantiates a new PuzzleRequestBuilder and sets the default values.
func NewPuzzleRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PuzzleRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewPuzzleRequestBuilderInternal(urlParams, requestAdapter)
}
// Daily the daily property
// returns a *PuzzleDailyRequestBuilder when successful
func (m *PuzzleRequestBuilder) Daily()(*PuzzleDailyRequestBuilder) {
    return NewPuzzleDailyRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Dashboard the dashboard property
// returns a *PuzzleDashboardRequestBuilder when successful
func (m *PuzzleRequestBuilder) Dashboard()(*PuzzleDashboardRequestBuilder) {
    return NewPuzzleDashboardRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Next the next property
// returns a *PuzzleNextRequestBuilder when successful
func (m *PuzzleRequestBuilder) Next()(*PuzzleNextRequestBuilder) {
    return NewPuzzleNextRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Replay the replay property
// returns a *PuzzleReplayRequestBuilder when successful
func (m *PuzzleRequestBuilder) Replay()(*PuzzleReplayRequestBuilder) {
    return NewPuzzleReplayRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
