// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7 "github.com/atye/golichess/kiota/models"
)

// RacerRacerItemRequestBuilder builds and executes requests for operations under \api\racer\{id}
type RacerRacerItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// RacerRacerItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type RacerRacerItemRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewRacerRacerItemRequestBuilderInternal instantiates a new RacerRacerItemRequestBuilder and sets the default values.
func NewRacerRacerItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*RacerRacerItemRequestBuilder) {
    m := &RacerRacerItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/racer/{id}", pathParameters),
    }
    return m
}
// NewRacerRacerItemRequestBuilder instantiates a new RacerRacerItemRequestBuilder and sets the default values.
func NewRacerRacerItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*RacerRacerItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewRacerRacerItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get the results of a [puzzle race](https://lichess.org/racer).Returns information about players, puzzles, and the current status of the race.- <https://lichess.org/racer>Note that Lichess puzzle races are not persisted, and are only availablefor 30 minutes. After that delay, they are permanently deleted.
// returns a PuzzleRaceResultsable when successful
// returns a NotFound error when the service returns a 404 status code
func (m *RacerRacerItemRequestBuilder) Get(ctx context.Context, requestConfiguration *RacerRacerItemRequestBuilderGetRequestConfiguration)(i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.PuzzleRaceResultsable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "404": i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.CreateNotFoundFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.CreatePuzzleRaceResultsFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.PuzzleRaceResultsable), nil
}
// ToGetRequestInformation get the results of a [puzzle race](https://lichess.org/racer).Returns information about players, puzzles, and the current status of the race.- <https://lichess.org/racer>Note that Lichess puzzle races are not persisted, and are only availablefor 30 minutes. After that delay, they are permanently deleted.
// returns a *RequestInformation when successful
func (m *RacerRacerItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *RacerRacerItemRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *RacerRacerItemRequestBuilder when successful
func (m *RacerRacerItemRequestBuilder) WithUrl(rawUrl string)(*RacerRacerItemRequestBuilder) {
    return NewRacerRacerItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
