// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7 "github.com/atye/golichess/kiota/models"
)

// RelUnfollowWithUsernameItemRequestBuilder builds and executes requests for operations under \api\rel\unfollow\{username}
type RelUnfollowWithUsernameItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// RelUnfollowWithUsernameItemRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type RelUnfollowWithUsernameItemRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewRelUnfollowWithUsernameItemRequestBuilderInternal instantiates a new RelUnfollowWithUsernameItemRequestBuilder and sets the default values.
func NewRelUnfollowWithUsernameItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*RelUnfollowWithUsernameItemRequestBuilder) {
    m := &RelUnfollowWithUsernameItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/rel/unfollow/{username}", pathParameters),
    }
    return m
}
// NewRelUnfollowWithUsernameItemRequestBuilder instantiates a new RelUnfollowWithUsernameItemRequestBuilder and sets the default values.
func NewRelUnfollowWithUsernameItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*RelUnfollowWithUsernameItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewRelUnfollowWithUsernameItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Post unfollow a player, removing them from your list of Lichess friends.
// returns a Okable when successful
func (m *RelUnfollowWithUsernameItemRequestBuilder) Post(ctx context.Context, requestConfiguration *RelUnfollowWithUsernameItemRequestBuilderPostRequestConfiguration)(i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.Okable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.CreateOkFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.Okable), nil
}
// ToPostRequestInformation unfollow a player, removing them from your list of Lichess friends.
// returns a *RequestInformation when successful
func (m *RelUnfollowWithUsernameItemRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *RelUnfollowWithUsernameItemRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *RelUnfollowWithUsernameItemRequestBuilder when successful
func (m *RelUnfollowWithUsernameItemRequestBuilder) WithUrl(rawUrl string)(*RelUnfollowWithUsernameItemRequestBuilder) {
    return NewRelUnfollowWithUsernameItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
