// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// StudyByWithUsernameItemRequestBuilder builds and executes requests for operations under \api\study\by\{username}
type StudyByWithUsernameItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// StudyByWithUsernameItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type StudyByWithUsernameItemRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewStudyByWithUsernameItemRequestBuilderInternal instantiates a new StudyByWithUsernameItemRequestBuilder and sets the default values.
func NewStudyByWithUsernameItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*StudyByWithUsernameItemRequestBuilder) {
    m := &StudyByWithUsernameItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/study/by/{username}", pathParameters),
    }
    return m
}
// NewStudyByWithUsernameItemRequestBuilder instantiates a new StudyByWithUsernameItemRequestBuilder and sets the default values.
func NewStudyByWithUsernameItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*StudyByWithUsernameItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewStudyByWithUsernameItemRequestBuilderInternal(urlParams, requestAdapter)
}
// ExportPgn the exportPgn property
// returns a *StudyByItemExportPgnRequestBuilder when successful
func (m *StudyByWithUsernameItemRequestBuilder) ExportPgn()(*StudyByItemExportPgnRequestBuilder) {
    return NewStudyByItemExportPgnRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Get get metadata (name and dates) of all studies of a user.If authenticated, then all public, unlisted, and private studies are included.If not, only public (non-unlisted) studies are included.Studies are streamed as [ndjson](#description/streaming-with-nd-json).
// returns a []byte when successful
func (m *StudyByWithUsernameItemRequestBuilder) Get(ctx context.Context, requestConfiguration *StudyByWithUsernameItemRequestBuilderGetRequestConfiguration)([]byte, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendPrimitive(ctx, requestInfo, "[]byte", nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.([]byte), nil
}
// ToGetRequestInformation get metadata (name and dates) of all studies of a user.If authenticated, then all public, unlisted, and private studies are included.If not, only public (non-unlisted) studies are included.Studies are streamed as [ndjson](#description/streaming-with-nd-json).
// returns a *RequestInformation when successful
func (m *StudyByWithUsernameItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *StudyByWithUsernameItemRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/x-ndjson")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *StudyByWithUsernameItemRequestBuilder when successful
func (m *StudyByWithUsernameItemRequestBuilder) WithUrl(rawUrl string)(*StudyByWithUsernameItemRequestBuilder) {
    return NewStudyByWithUsernameItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
