// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7 "github.com/atye/golichess/kiota/models"
)

// TeamItemRequestsRequestBuilder builds and executes requests for operations under \api\team\{teamId}\requests
type TeamItemRequestsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// TeamItemRequestsRequestBuilderGetQueryParameters get pending join requests of your team
type TeamItemRequestsRequestBuilderGetQueryParameters struct {
    // Get the declined join requests
    Declined *bool "uriparametername:\"declined\""
}
// TeamItemRequestsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type TeamItemRequestsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *TeamItemRequestsRequestBuilderGetQueryParameters
}
// NewTeamItemRequestsRequestBuilderInternal instantiates a new TeamItemRequestsRequestBuilder and sets the default values.
func NewTeamItemRequestsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*TeamItemRequestsRequestBuilder) {
    m := &TeamItemRequestsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/team/{teamId}/requests{?declined*}", pathParameters),
    }
    return m
}
// NewTeamItemRequestsRequestBuilder instantiates a new TeamItemRequestsRequestBuilder and sets the default values.
func NewTeamItemRequestsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*TeamItemRequestsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewTeamItemRequestsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get pending join requests of your team
// returns a []TeamRequestWithUserable when successful
func (m *TeamItemRequestsRequestBuilder) Get(ctx context.Context, requestConfiguration *TeamItemRequestsRequestBuilderGetRequestConfiguration)([]i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.TeamRequestWithUserable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.CreateTeamRequestWithUserFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    val := make([]i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.TeamRequestWithUserable, len(res))
    for i, v := range res {
        if v != nil {
            val[i] = v.(i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.TeamRequestWithUserable)
        }
    }
    return val, nil
}
// ToGetRequestInformation get pending join requests of your team
// returns a *RequestInformation when successful
func (m *TeamItemRequestsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *TeamItemRequestsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *TeamItemRequestsRequestBuilder when successful
func (m *TeamItemRequestsRequestBuilder) WithUrl(rawUrl string)(*TeamItemRequestsRequestBuilder) {
    return NewTeamItemRequestsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
