// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
	"context"
	i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7 "github.com/atye/golichess/kiota/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// TeamSearchRequestBuilder builds and executes requests for operations under \api\team\search
type TeamSearchRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// TeamSearchRequestBuilderGetQueryParameters paginator of team search results for a keyword.
type TeamSearchRequestBuilderGetQueryParameters struct {
	Page *int32  "uriparametername:\"page\""
	Text *string "uriparametername:\"text\""
}

// TeamSearchRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type TeamSearchRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
	// Request query parameters
	QueryParameters *TeamSearchRequestBuilderGetQueryParameters
}

// NewTeamSearchRequestBuilderInternal instantiates a new TeamSearchRequestBuilder and sets the default values.
func NewTeamSearchRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *TeamSearchRequestBuilder {
	m := &TeamSearchRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/team/search{?page*,text*}", pathParameters),
	}
	return m
}

// NewTeamSearchRequestBuilder instantiates a new TeamSearchRequestBuilder and sets the default values.
func NewTeamSearchRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *TeamSearchRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewTeamSearchRequestBuilderInternal(urlParams, requestAdapter)
}

// Get paginator of team search results for a keyword.
// returns a TeamPaginatorJsonable when successful
func (m *TeamSearchRequestBuilder) Get(ctx context.Context, requestConfiguration *TeamSearchRequestBuilderGetRequestConfiguration) (i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.TeamPaginatorJsonable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.CreateTeamPaginatorJsonFromDiscriminatorValue, nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.TeamPaginatorJsonable), nil
}

// ToGetRequestInformation paginator of team search results for a keyword.
// returns a *RequestInformation when successful
func (m *TeamSearchRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *TeamSearchRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		if requestConfiguration.QueryParameters != nil {
			requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
		}
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *TeamSearchRequestBuilder when successful
func (m *TeamSearchRequestBuilder) WithUrl(rawUrl string) *TeamSearchRequestBuilder {
	return NewTeamSearchRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
