// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
	"context"
	i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7 "github.com/atye/golichess/kiota/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// TokenAdminChallengeRequestBuilder builds and executes requests for operations under \api\token\admin-challenge
type TokenAdminChallengeRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// TokenAdminChallengeRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type TokenAdminChallengeRequestBuilderPostRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}

// NewTokenAdminChallengeRequestBuilderInternal instantiates a new TokenAdminChallengeRequestBuilder and sets the default values.
func NewTokenAdminChallengeRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *TokenAdminChallengeRequestBuilder {
	m := &TokenAdminChallengeRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/token/admin-challenge", pathParameters),
	}
	return m
}

// NewTokenAdminChallengeRequestBuilder instantiates a new TokenAdminChallengeRequestBuilder and sets the default values.
func NewTokenAdminChallengeRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *TokenAdminChallengeRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewTokenAdminChallengeRequestBuilderInternal(urlParams, requestAdapter)
}

// Post **This endpoint can only be used by Lichess administrators. It will not work if you do not have the appropriate permissions.** Tournament organizers should instead use [OAuth](#tag/OAuth) to obtain `challenge:write` tokens from users in order to perform bulk pairing.*Create and obtain `challenge:write` tokens for multiple users.If a similar token already exists for a user, it is reused. This endpoint is idempotent.
// Deprecated: This method is obsolete. Use PostAsAdminChallengePostResponse instead.
// returns a TokenAdminChallengeResponseable when successful
// returns a ErrorEscaped error when the service returns a 400 status code
func (m *TokenAdminChallengeRequestBuilder) Post(ctx context.Context, body TokenAdminChallengePostRequestBodyable, requestConfiguration *TokenAdminChallengeRequestBuilderPostRequestConfiguration) (TokenAdminChallengeResponseable, error) {
	requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.CreateErrorEscapedFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateTokenAdminChallengeResponseFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(TokenAdminChallengeResponseable), nil
}

// PostAsAdminChallengePostResponse **This endpoint can only be used by Lichess administrators. It will not work if you do not have the appropriate permissions.** Tournament organizers should instead use [OAuth](#tag/OAuth) to obtain `challenge:write` tokens from users in order to perform bulk pairing.*Create and obtain `challenge:write` tokens for multiple users.If a similar token already exists for a user, it is reused. This endpoint is idempotent.
// returns a TokenAdminChallengePostResponseable when successful
// returns a ErrorEscaped error when the service returns a 400 status code
func (m *TokenAdminChallengeRequestBuilder) PostAsAdminChallengePostResponse(ctx context.Context, body TokenAdminChallengePostRequestBodyable, requestConfiguration *TokenAdminChallengeRequestBuilderPostRequestConfiguration) (TokenAdminChallengePostResponseable, error) {
	requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": i9c7bd2a4616e157afccf66fb4f0e43fe37d5e83f0fbb4153877fc42d06fad6f7.CreateErrorEscapedFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateTokenAdminChallengePostResponseFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(TokenAdminChallengePostResponseable), nil
}

// ToPostRequestInformation **This endpoint can only be used by Lichess administrators. It will not work if you do not have the appropriate permissions.** Tournament organizers should instead use [OAuth](#tag/OAuth) to obtain `challenge:write` tokens from users in order to perform bulk pairing.*Create and obtain `challenge:write` tokens for multiple users.If a similar token already exists for a user, it is reused. This endpoint is idempotent.
// returns a *RequestInformation when successful
func (m *TokenAdminChallengeRequestBuilder) ToPostRequestInformation(ctx context.Context, body TokenAdminChallengePostRequestBodyable, requestConfiguration *TokenAdminChallengeRequestBuilderPostRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/x-www-form-urlencoded", body)
	if err != nil {
		return nil, err
	}
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *TokenAdminChallengeRequestBuilder when successful
func (m *TokenAdminChallengeRequestBuilder) WithUrl(rawUrl string) *TokenAdminChallengeRequestBuilder {
	return NewTokenAdminChallengeRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
