// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// TournamentTeamBattleRequestBuilder builds and executes requests for operations under \api\tournament\team-battle
type TournamentTeamBattleRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ById gets an item from the github.com/atye/golichess/kiota.api.tournament.teamBattle.item collection
// returns a *TournamentTeamBattleTeamBattleItemRequestBuilder when successful
func (m *TournamentTeamBattleRequestBuilder) ById(id string)(*TournamentTeamBattleTeamBattleItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if id != "" {
        urlTplParams["id"] = id
    }
    return NewTournamentTeamBattleTeamBattleItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewTournamentTeamBattleRequestBuilderInternal instantiates a new TournamentTeamBattleRequestBuilder and sets the default values.
func NewTournamentTeamBattleRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*TournamentTeamBattleRequestBuilder) {
    m := &TournamentTeamBattleRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/tournament/team-battle", pathParameters),
    }
    return m
}
// NewTournamentTeamBattleRequestBuilder instantiates a new TournamentTeamBattleRequestBuilder and sets the default values.
func NewTournamentTeamBattleRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*TournamentTeamBattleRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewTournamentTeamBattleRequestBuilderInternal(urlParams, requestAdapter)
}
