// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type BroadcastPlayerEntryWithFideAndGames struct {
	BroadcastPlayerEntry
	// The fide property
	fide BroadcastPlayerEntryWithFideAndGames_fideable
	// List of games played by the player in the broadcast tournament
	games []BroadcastGameEntryable
}

// NewBroadcastPlayerEntryWithFideAndGames instantiates a new BroadcastPlayerEntryWithFideAndGames and sets the default values.
func NewBroadcastPlayerEntryWithFideAndGames() *BroadcastPlayerEntryWithFideAndGames {
	m := &BroadcastPlayerEntryWithFideAndGames{
		BroadcastPlayerEntry: *NewBroadcastPlayerEntry(),
	}
	return m
}

// CreateBroadcastPlayerEntryWithFideAndGamesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateBroadcastPlayerEntryWithFideAndGamesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewBroadcastPlayerEntryWithFideAndGames(), nil
}

// GetFide gets the fide property value. The fide property
// returns a BroadcastPlayerEntryWithFideAndGames_fideable when successful
func (m *BroadcastPlayerEntryWithFideAndGames) GetFide() BroadcastPlayerEntryWithFideAndGames_fideable {
	return m.fide
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *BroadcastPlayerEntryWithFideAndGames) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.BroadcastPlayerEntry.GetFieldDeserializers()
	res["fide"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateBroadcastPlayerEntryWithFideAndGames_fideFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetFide(val.(BroadcastPlayerEntryWithFideAndGames_fideable))
		}
		return nil
	}
	res["games"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateBroadcastGameEntryFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]BroadcastGameEntryable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(BroadcastGameEntryable)
				}
			}
			m.SetGames(res)
		}
		return nil
	}
	return res
}

// GetGames gets the games property value. List of games played by the player in the broadcast tournament
// returns a []BroadcastGameEntryable when successful
func (m *BroadcastPlayerEntryWithFideAndGames) GetGames() []BroadcastGameEntryable {
	return m.games
}

// Serialize serializes information the current object
func (m *BroadcastPlayerEntryWithFideAndGames) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.BroadcastPlayerEntry.Serialize(writer)
	if err != nil {
		return err
	}
	{
		err = writer.WriteObjectValue("fide", m.GetFide())
		if err != nil {
			return err
		}
	}
	if m.GetGames() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetGames()))
		for i, v := range m.GetGames() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err = writer.WriteCollectionOfObjectValues("games", cast)
		if err != nil {
			return err
		}
	}
	return nil
}

// SetFide sets the fide property value. The fide property
func (m *BroadcastPlayerEntryWithFideAndGames) SetFide(value BroadcastPlayerEntryWithFideAndGames_fideable) {
	m.fide = value
}

// SetGames sets the games property value. List of games played by the player in the broadcast tournament
func (m *BroadcastPlayerEntryWithFideAndGames) SetGames(value []BroadcastGameEntryable) {
	m.games = value
}

type BroadcastPlayerEntryWithFideAndGamesable interface {
	BroadcastPlayerEntryable
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetFide() BroadcastPlayerEntryWithFideAndGames_fideable
	GetGames() []BroadcastGameEntryable
	SetFide(value BroadcastPlayerEntryWithFideAndGames_fideable)
	SetGames(value []BroadcastGameEntryable)
}
