// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ChallengeUser struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// See [available flair list and images](https://github.com/lichess-org/lila/tree/master/public/flair)
	flair *string
	// The id property
	id *string
	// The lag property
	lag *int32
	// The name property
	name *string
	// The online property
	online *bool
	// Use patronColor value instead to determine if player is a patron.
	// Deprecated:
	patron *bool
	// Players can choose a color for their Patron wings.See [here for the color mappings](https://github.com/lichess-org/lila/blob/master/ui/lib/css/abstract/_patron-colors.scss).The presence of this field indicates the player is an active Patron.
	patronColor *int32
	// The provisional property
	provisional *bool
	// The rating property
	rating *int32
	// only appears if the user is a titled player or a bot user
	title *Title
}

// NewChallengeUser instantiates a new ChallengeUser and sets the default values.
func NewChallengeUser() *ChallengeUser {
	m := &ChallengeUser{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateChallengeUserFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateChallengeUserFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewChallengeUser(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ChallengeUser) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *ChallengeUser) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["flair"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetFlair(val)
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["lag"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLag(val)
		}
		return nil
	}
	res["name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetName(val)
		}
		return nil
	}
	res["online"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetOnline(val)
		}
		return nil
	}
	res["patron"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPatron(val)
		}
		return nil
	}
	res["patronColor"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPatronColor(val)
		}
		return nil
	}
	res["provisional"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProvisional(val)
		}
		return nil
	}
	res["rating"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRating(val)
		}
		return nil
	}
	res["title"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseTitle)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTitle(val.(*Title))
		}
		return nil
	}
	return res
}

// GetFlair gets the flair property value. See [available flair list and images](https://github.com/lichess-org/lila/tree/master/public/flair)
// returns a *string when successful
func (m *ChallengeUser) GetFlair() *string {
	return m.flair
}

// GetId gets the id property value. The id property
// returns a *string when successful
func (m *ChallengeUser) GetId() *string {
	return m.id
}

// GetLag gets the lag property value. The lag property
// returns a *int32 when successful
func (m *ChallengeUser) GetLag() *int32 {
	return m.lag
}

// GetName gets the name property value. The name property
// returns a *string when successful
func (m *ChallengeUser) GetName() *string {
	return m.name
}

// GetOnline gets the online property value. The online property
// returns a *bool when successful
func (m *ChallengeUser) GetOnline() *bool {
	return m.online
}

// GetPatron gets the patron property value. Use patronColor value instead to determine if player is a patron.
// Deprecated:
// returns a *bool when successful
func (m *ChallengeUser) GetPatron() *bool {
	return m.patron
}

// GetPatronColor gets the patronColor property value. Players can choose a color for their Patron wings.See [here for the color mappings](https://github.com/lichess-org/lila/blob/master/ui/lib/css/abstract/_patron-colors.scss).The presence of this field indicates the player is an active Patron.
// returns a *int32 when successful
func (m *ChallengeUser) GetPatronColor() *int32 {
	return m.patronColor
}

// GetProvisional gets the provisional property value. The provisional property
// returns a *bool when successful
func (m *ChallengeUser) GetProvisional() *bool {
	return m.provisional
}

// GetRating gets the rating property value. The rating property
// returns a *int32 when successful
func (m *ChallengeUser) GetRating() *int32 {
	return m.rating
}

// GetTitle gets the title property value. only appears if the user is a titled player or a bot user
// returns a *Title when successful
func (m *ChallengeUser) GetTitle() *Title {
	return m.title
}

// Serialize serializes information the current object
func (m *ChallengeUser) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("flair", m.GetFlair())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("id", m.GetId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("lag", m.GetLag())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("name", m.GetName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("online", m.GetOnline())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("patron", m.GetPatron())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("patronColor", m.GetPatronColor())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("provisional", m.GetProvisional())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("rating", m.GetRating())
		if err != nil {
			return err
		}
	}
	if m.GetTitle() != nil {
		cast := (*m.GetTitle()).String()
		err := writer.WriteStringValue("title", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ChallengeUser) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetFlair sets the flair property value. See [available flair list and images](https://github.com/lichess-org/lila/tree/master/public/flair)
func (m *ChallengeUser) SetFlair(value *string) {
	m.flair = value
}

// SetId sets the id property value. The id property
func (m *ChallengeUser) SetId(value *string) {
	m.id = value
}

// SetLag sets the lag property value. The lag property
func (m *ChallengeUser) SetLag(value *int32) {
	m.lag = value
}

// SetName sets the name property value. The name property
func (m *ChallengeUser) SetName(value *string) {
	m.name = value
}

// SetOnline sets the online property value. The online property
func (m *ChallengeUser) SetOnline(value *bool) {
	m.online = value
}

// SetPatron sets the patron property value. Use patronColor value instead to determine if player is a patron.
// Deprecated:
func (m *ChallengeUser) SetPatron(value *bool) {
	m.patron = value
}

// SetPatronColor sets the patronColor property value. Players can choose a color for their Patron wings.See [here for the color mappings](https://github.com/lichess-org/lila/blob/master/ui/lib/css/abstract/_patron-colors.scss).The presence of this field indicates the player is an active Patron.
func (m *ChallengeUser) SetPatronColor(value *int32) {
	m.patronColor = value
}

// SetProvisional sets the provisional property value. The provisional property
func (m *ChallengeUser) SetProvisional(value *bool) {
	m.provisional = value
}

// SetRating sets the rating property value. The rating property
func (m *ChallengeUser) SetRating(value *int32) {
	m.rating = value
}

// SetTitle sets the title property value. only appears if the user is a titled player or a bot user
func (m *ChallengeUser) SetTitle(value *Title) {
	m.title = value
}

type ChallengeUserable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetFlair() *string
	GetId() *string
	GetLag() *int32
	GetName() *string
	GetOnline() *bool
	GetPatron() *bool
	GetPatronColor() *int32
	GetProvisional() *bool
	GetRating() *int32
	GetTitle() *Title
	SetFlair(value *string)
	SetId(value *string)
	SetLag(value *int32)
	SetName(value *string)
	SetOnline(value *bool)
	SetPatron(value *bool)
	SetPatronColor(value *int32)
	SetProvisional(value *bool)
	SetRating(value *int32)
	SetTitle(value *Title)
}
