// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

type GameMoveAnalysis_judgment_name int

const (
	INACCURACY_GAMEMOVEANALYSIS_JUDGMENT_NAME GameMoveAnalysis_judgment_name = iota
	MISTAKE_GAMEMOVEANALYSIS_JUDGMENT_NAME
	BLUNDER_GAMEMOVEANALYSIS_JUDGMENT_NAME
)

func (i GameMoveAnalysis_judgment_name) String() string {
	return []string{"Inaccuracy", "Mistake", "Blunder"}[i]
}

func ParseGameMoveAnalysis_judgment_name(v string) (any, error) {
	result := INACCURACY_GAMEMOVEANALYSIS_JUDGMENT_NAME
	switch v {
	case "Inaccuracy":
		result = INACCURACY_GAMEMOVEANALYSIS_JUDGMENT_NAME
	case "Mistake":
		result = MISTAKE_GAMEMOVEANALYSIS_JUDGMENT_NAME
	case "Blunder":
		result = BLUNDER_GAMEMOVEANALYSIS_JUDGMENT_NAME
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeGameMoveAnalysis_judgment_name(values []GameMoveAnalysis_judgment_name) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i GameMoveAnalysis_judgment_name) isMultiValue() bool {
	return false
}
