// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type OpeningExplorerMasters_topGames struct {
	OpeningExplorerMastersGame
	// The uci property
	uci *string
}

// NewOpeningExplorerMasters_topGames instantiates a new OpeningExplorerMasters_topGames and sets the default values.
func NewOpeningExplorerMasters_topGames() *OpeningExplorerMasters_topGames {
	m := &OpeningExplorerMasters_topGames{
		OpeningExplorerMastersGame: *NewOpeningExplorerMastersGame(),
	}
	return m
}

// CreateOpeningExplorerMasters_topGamesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOpeningExplorerMasters_topGamesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewOpeningExplorerMasters_topGames(), nil
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *OpeningExplorerMasters_topGames) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.OpeningExplorerMastersGame.GetFieldDeserializers()
	res["uci"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUci(val)
		}
		return nil
	}
	return res
}

// GetUci gets the uci property value. The uci property
// returns a *string when successful
func (m *OpeningExplorerMasters_topGames) GetUci() *string {
	return m.uci
}

// Serialize serializes information the current object
func (m *OpeningExplorerMasters_topGames) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.OpeningExplorerMastersGame.Serialize(writer)
	if err != nil {
		return err
	}
	{
		err = writer.WriteStringValue("uci", m.GetUci())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetUci sets the uci property value. The uci property
func (m *OpeningExplorerMasters_topGames) SetUci(value *string) {
	m.uci = value
}

type OpeningExplorerMasters_topGamesable interface {
	OpeningExplorerMastersGameable
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetUci() *string
	SetUci(value *string)
}
