// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type PuzzleModePerf struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The runs property
	runs *int32
	// The score property
	score *int32
}

// NewPuzzleModePerf instantiates a new PuzzleModePerf and sets the default values.
func NewPuzzleModePerf() *PuzzleModePerf {
	m := &PuzzleModePerf{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreatePuzzleModePerfFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePuzzleModePerfFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewPuzzleModePerf(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PuzzleModePerf) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *PuzzleModePerf) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["runs"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRuns(val)
		}
		return nil
	}
	res["score"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetScore(val)
		}
		return nil
	}
	return res
}

// GetRuns gets the runs property value. The runs property
// returns a *int32 when successful
func (m *PuzzleModePerf) GetRuns() *int32 {
	return m.runs
}

// GetScore gets the score property value. The score property
// returns a *int32 when successful
func (m *PuzzleModePerf) GetScore() *int32 {
	return m.score
}

// Serialize serializes information the current object
func (m *PuzzleModePerf) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt32Value("runs", m.GetRuns())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("score", m.GetScore())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PuzzleModePerf) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetRuns sets the runs property value. The runs property
func (m *PuzzleModePerf) SetRuns(value *int32) {
	m.runs = value
}

// SetScore sets the score property value. The score property
func (m *PuzzleModePerf) SetScore(value *int32) {
	m.score = value
}

type PuzzleModePerfable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetRuns() *int32
	GetScore() *int32
	SetRuns(value *int32)
	SetScore(value *int32)
}
