// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type StudyImportPgnChapters_chapters_players struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The player name
    name *string
    // The player rating
    rating *int32
}
// NewStudyImportPgnChapters_chapters_players instantiates a new StudyImportPgnChapters_chapters_players and sets the default values.
func NewStudyImportPgnChapters_chapters_players()(*StudyImportPgnChapters_chapters_players) {
    m := &StudyImportPgnChapters_chapters_players{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateStudyImportPgnChapters_chapters_playersFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateStudyImportPgnChapters_chapters_playersFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewStudyImportPgnChapters_chapters_players(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *StudyImportPgnChapters_chapters_players) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *StudyImportPgnChapters_chapters_players) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["rating"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRating(val)
        }
        return nil
    }
    return res
}
// GetName gets the name property value. The player name
// returns a *string when successful
func (m *StudyImportPgnChapters_chapters_players) GetName()(*string) {
    return m.name
}
// GetRating gets the rating property value. The player rating
// returns a *int32 when successful
func (m *StudyImportPgnChapters_chapters_players) GetRating()(*int32) {
    return m.rating
}
// Serialize serializes information the current object
func (m *StudyImportPgnChapters_chapters_players) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("rating", m.GetRating())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *StudyImportPgnChapters_chapters_players) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetName sets the name property value. The player name
func (m *StudyImportPgnChapters_chapters_players) SetName(value *string)() {
    m.name = value
}
// SetRating sets the rating property value. The player rating
func (m *StudyImportPgnChapters_chapters_players) SetRating(value *int32)() {
    m.rating = value
}
type StudyImportPgnChapters_chapters_playersable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetName()(*string)
    GetRating()(*int32)
    SetName(value *string)()
    SetRating(value *int32)()
}
