// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type TimelineEntryTeamCreate struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The data property
    data TimelineEntryTeamCreate_dataable
    // The date property
    date *float64
    // The type property
    typeEscaped *TimelineEntryTeamCreate_type
}
// NewTimelineEntryTeamCreate instantiates a new TimelineEntryTeamCreate and sets the default values.
func NewTimelineEntryTeamCreate()(*TimelineEntryTeamCreate) {
    m := &TimelineEntryTeamCreate{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateTimelineEntryTeamCreateFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTimelineEntryTeamCreateFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTimelineEntryTeamCreate(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *TimelineEntryTeamCreate) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetData gets the data property value. The data property
// returns a TimelineEntryTeamCreate_dataable when successful
func (m *TimelineEntryTeamCreate) GetData()(TimelineEntryTeamCreate_dataable) {
    return m.data
}
// GetDate gets the date property value. The date property
// returns a *float64 when successful
func (m *TimelineEntryTeamCreate) GetDate()(*float64) {
    return m.date
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *TimelineEntryTeamCreate) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateTimelineEntryTeamCreate_dataFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetData(val.(TimelineEntryTeamCreate_dataable))
        }
        return nil
    }
    res["date"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDate(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseTimelineEntryTeamCreate_type)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val.(*TimelineEntryTeamCreate_type))
        }
        return nil
    }
    return res
}
// GetTypeEscaped gets the type property value. The type property
// returns a *TimelineEntryTeamCreate_type when successful
func (m *TimelineEntryTeamCreate) GetTypeEscaped()(*TimelineEntryTeamCreate_type) {
    return m.typeEscaped
}
// Serialize serializes information the current object
func (m *TimelineEntryTeamCreate) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("data", m.GetData())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("date", m.GetDate())
        if err != nil {
            return err
        }
    }
    if m.GetTypeEscaped() != nil {
        cast := (*m.GetTypeEscaped()).String()
        err := writer.WriteStringValue("type", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *TimelineEntryTeamCreate) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetData sets the data property value. The data property
func (m *TimelineEntryTeamCreate) SetData(value TimelineEntryTeamCreate_dataable)() {
    m.data = value
}
// SetDate sets the date property value. The date property
func (m *TimelineEntryTeamCreate) SetDate(value *float64)() {
    m.date = value
}
// SetTypeEscaped sets the type property value. The type property
func (m *TimelineEntryTeamCreate) SetTypeEscaped(value *TimelineEntryTeamCreate_type)() {
    m.typeEscaped = value
}
type TimelineEntryTeamCreateable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetData()(TimelineEntryTeamCreate_dataable)
    GetDate()(*float64)
    GetTypeEscaped()(*TimelineEntryTeamCreate_type)
    SetData(value TimelineEntryTeamCreate_dataable)()
    SetDate(value *float64)()
    SetTypeEscaped(value *TimelineEntryTeamCreate_type)()
}
