// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type TimelineEntryTeamCreate_type int

const (
    TEAMCREATE_TIMELINEENTRYTEAMCREATE_TYPE TimelineEntryTeamCreate_type = iota
)

func (i TimelineEntryTeamCreate_type) String() string {
    return []string{"team-create"}[i]
}
func ParseTimelineEntryTeamCreate_type(v string) (any, error) {
    result := TEAMCREATE_TIMELINEENTRYTEAMCREATE_TYPE
    switch v {
        case "team-create":
            result = TEAMCREATE_TIMELINEENTRYTEAMCREATE_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeTimelineEntryTeamCreate_type(values []TimelineEntryTeamCreate_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i TimelineEntryTeamCreate_type) isMultiValue() bool {
    return false
}
