// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type TimelineEntryTeamJoin_data struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The teamId property
    teamId *string
    // The userId property
    userId *string
}
// NewTimelineEntryTeamJoin_data instantiates a new TimelineEntryTeamJoin_data and sets the default values.
func NewTimelineEntryTeamJoin_data()(*TimelineEntryTeamJoin_data) {
    m := &TimelineEntryTeamJoin_data{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateTimelineEntryTeamJoin_dataFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTimelineEntryTeamJoin_dataFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTimelineEntryTeamJoin_data(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *TimelineEntryTeamJoin_data) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *TimelineEntryTeamJoin_data) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["teamId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTeamId(val)
        }
        return nil
    }
    res["userId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUserId(val)
        }
        return nil
    }
    return res
}
// GetTeamId gets the teamId property value. The teamId property
// returns a *string when successful
func (m *TimelineEntryTeamJoin_data) GetTeamId()(*string) {
    return m.teamId
}
// GetUserId gets the userId property value. The userId property
// returns a *string when successful
func (m *TimelineEntryTeamJoin_data) GetUserId()(*string) {
    return m.userId
}
// Serialize serializes information the current object
func (m *TimelineEntryTeamJoin_data) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("teamId", m.GetTeamId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("userId", m.GetUserId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *TimelineEntryTeamJoin_data) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetTeamId sets the teamId property value. The teamId property
func (m *TimelineEntryTeamJoin_data) SetTeamId(value *string)() {
    m.teamId = value
}
// SetUserId sets the userId property value. The userId property
func (m *TimelineEntryTeamJoin_data) SetUserId(value *string)() {
    m.userId = value
}
type TimelineEntryTeamJoin_dataable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetTeamId()(*string)
    GetUserId()(*string)
    SetTeamId(value *string)()
    SetUserId(value *string)()
}
