// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type TimelineEntryFollow_type int

const (
    FOLLOW_TIMELINEENTRYFOLLOW_TYPE TimelineEntryFollow_type = iota
)

func (i TimelineEntryFollow_type) String() string {
    return []string{"follow"}[i]
}
func ParseTimelineEntryFollow_type(v string) (any, error) {
    result := FOLLOW_TIMELINEENTRYFOLLOW_TYPE
    switch v {
        case "follow":
            result = FOLLOW_TIMELINEENTRYFOLLOW_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeTimelineEntryFollow_type(values []TimelineEntryFollow_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i TimelineEntryFollow_type) isMultiValue() bool {
    return false
}
