// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type TimelineEntrySimul_data struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The simulId property
    simulId *string
    // The simulName property
    simulName *string
    // The userId property
    userId *string
}
// NewTimelineEntrySimul_data instantiates a new TimelineEntrySimul_data and sets the default values.
func NewTimelineEntrySimul_data()(*TimelineEntrySimul_data) {
    m := &TimelineEntrySimul_data{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateTimelineEntrySimul_dataFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTimelineEntrySimul_dataFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTimelineEntrySimul_data(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *TimelineEntrySimul_data) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *TimelineEntrySimul_data) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["simulId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSimulId(val)
        }
        return nil
    }
    res["simulName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSimulName(val)
        }
        return nil
    }
    res["userId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUserId(val)
        }
        return nil
    }
    return res
}
// GetSimulId gets the simulId property value. The simulId property
// returns a *string when successful
func (m *TimelineEntrySimul_data) GetSimulId()(*string) {
    return m.simulId
}
// GetSimulName gets the simulName property value. The simulName property
// returns a *string when successful
func (m *TimelineEntrySimul_data) GetSimulName()(*string) {
    return m.simulName
}
// GetUserId gets the userId property value. The userId property
// returns a *string when successful
func (m *TimelineEntrySimul_data) GetUserId()(*string) {
    return m.userId
}
// Serialize serializes information the current object
func (m *TimelineEntrySimul_data) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("simulId", m.GetSimulId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("simulName", m.GetSimulName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("userId", m.GetUserId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *TimelineEntrySimul_data) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetSimulId sets the simulId property value. The simulId property
func (m *TimelineEntrySimul_data) SetSimulId(value *string)() {
    m.simulId = value
}
// SetSimulName sets the simulName property value. The simulName property
func (m *TimelineEntrySimul_data) SetSimulName(value *string)() {
    m.simulName = value
}
// SetUserId sets the userId property value. The userId property
func (m *TimelineEntrySimul_data) SetUserId(value *string)() {
    m.userId = value
}
type TimelineEntrySimul_dataable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetSimulId()(*string)
    GetSimulName()(*string)
    GetUserId()(*string)
    SetSimulId(value *string)()
    SetSimulName(value *string)()
    SetUserId(value *string)()
}
