// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type TimelineEntryUblogPost_data struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The id property
    id *string
    // The slug property
    slug *string
    // The title property
    title *string
    // The userId property
    userId *string
}
// NewTimelineEntryUblogPost_data instantiates a new TimelineEntryUblogPost_data and sets the default values.
func NewTimelineEntryUblogPost_data()(*TimelineEntryUblogPost_data) {
    m := &TimelineEntryUblogPost_data{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateTimelineEntryUblogPost_dataFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTimelineEntryUblogPost_dataFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTimelineEntryUblogPost_data(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *TimelineEntryUblogPost_data) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *TimelineEntryUblogPost_data) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["slug"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSlug(val)
        }
        return nil
    }
    res["title"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTitle(val)
        }
        return nil
    }
    res["userId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUserId(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *TimelineEntryUblogPost_data) GetId()(*string) {
    return m.id
}
// GetSlug gets the slug property value. The slug property
// returns a *string when successful
func (m *TimelineEntryUblogPost_data) GetSlug()(*string) {
    return m.slug
}
// GetTitle gets the title property value. The title property
// returns a *string when successful
func (m *TimelineEntryUblogPost_data) GetTitle()(*string) {
    return m.title
}
// GetUserId gets the userId property value. The userId property
// returns a *string when successful
func (m *TimelineEntryUblogPost_data) GetUserId()(*string) {
    return m.userId
}
// Serialize serializes information the current object
func (m *TimelineEntryUblogPost_data) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("slug", m.GetSlug())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("title", m.GetTitle())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("userId", m.GetUserId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *TimelineEntryUblogPost_data) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetId sets the id property value. The id property
func (m *TimelineEntryUblogPost_data) SetId(value *string)() {
    m.id = value
}
// SetSlug sets the slug property value. The slug property
func (m *TimelineEntryUblogPost_data) SetSlug(value *string)() {
    m.slug = value
}
// SetTitle sets the title property value. The title property
func (m *TimelineEntryUblogPost_data) SetTitle(value *string)() {
    m.title = value
}
// SetUserId sets the userId property value. The userId property
func (m *TimelineEntryUblogPost_data) SetUserId(value *string)() {
    m.userId = value
}
type TimelineEntryUblogPost_dataable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetId()(*string)
    GetSlug()(*string)
    GetTitle()(*string)
    GetUserId()(*string)
    SetId(value *string)()
    SetSlug(value *string)()
    SetTitle(value *string)()
    SetUserId(value *string)()
}
