// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type TimelineEntrySimul_type int

const (
    SIMULCREATE_TIMELINEENTRYSIMUL_TYPE TimelineEntrySimul_type = iota
    SIMULJOIN_TIMELINEENTRYSIMUL_TYPE
)

func (i TimelineEntrySimul_type) String() string {
    return []string{"simul-create", "simul-join"}[i]
}
func ParseTimelineEntrySimul_type(v string) (any, error) {
    result := SIMULCREATE_TIMELINEENTRYSIMUL_TYPE
    switch v {
        case "simul-create":
            result = SIMULCREATE_TIMELINEENTRYSIMUL_TYPE
        case "simul-join":
            result = SIMULJOIN_TIMELINEENTRYSIMUL_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeTimelineEntrySimul_type(values []TimelineEntrySimul_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i TimelineEntrySimul_type) isMultiValue() bool {
    return false
}
