// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type UserActivity_tournaments_best struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The nbGames property
    nbGames *int32
    // The rank property
    rank *int32
    // The rankPercent property
    rankPercent *int32
    // The score property
    score *int32
    // The tournament property
    tournament UserActivity_tournaments_best_tournamentable
}
// NewUserActivity_tournaments_best instantiates a new UserActivity_tournaments_best and sets the default values.
func NewUserActivity_tournaments_best()(*UserActivity_tournaments_best) {
    m := &UserActivity_tournaments_best{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateUserActivity_tournaments_bestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateUserActivity_tournaments_bestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewUserActivity_tournaments_best(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *UserActivity_tournaments_best) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *UserActivity_tournaments_best) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["nbGames"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNbGames(val)
        }
        return nil
    }
    res["rank"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRank(val)
        }
        return nil
    }
    res["rankPercent"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRankPercent(val)
        }
        return nil
    }
    res["score"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetScore(val)
        }
        return nil
    }
    res["tournament"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateUserActivity_tournaments_best_tournamentFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTournament(val.(UserActivity_tournaments_best_tournamentable))
        }
        return nil
    }
    return res
}
// GetNbGames gets the nbGames property value. The nbGames property
// returns a *int32 when successful
func (m *UserActivity_tournaments_best) GetNbGames()(*int32) {
    return m.nbGames
}
// GetRank gets the rank property value. The rank property
// returns a *int32 when successful
func (m *UserActivity_tournaments_best) GetRank()(*int32) {
    return m.rank
}
// GetRankPercent gets the rankPercent property value. The rankPercent property
// returns a *int32 when successful
func (m *UserActivity_tournaments_best) GetRankPercent()(*int32) {
    return m.rankPercent
}
// GetScore gets the score property value. The score property
// returns a *int32 when successful
func (m *UserActivity_tournaments_best) GetScore()(*int32) {
    return m.score
}
// GetTournament gets the tournament property value. The tournament property
// returns a UserActivity_tournaments_best_tournamentable when successful
func (m *UserActivity_tournaments_best) GetTournament()(UserActivity_tournaments_best_tournamentable) {
    return m.tournament
}
// Serialize serializes information the current object
func (m *UserActivity_tournaments_best) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("nbGames", m.GetNbGames())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("rank", m.GetRank())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("rankPercent", m.GetRankPercent())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("score", m.GetScore())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("tournament", m.GetTournament())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *UserActivity_tournaments_best) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetNbGames sets the nbGames property value. The nbGames property
func (m *UserActivity_tournaments_best) SetNbGames(value *int32)() {
    m.nbGames = value
}
// SetRank sets the rank property value. The rank property
func (m *UserActivity_tournaments_best) SetRank(value *int32)() {
    m.rank = value
}
// SetRankPercent sets the rankPercent property value. The rankPercent property
func (m *UserActivity_tournaments_best) SetRankPercent(value *int32)() {
    m.rankPercent = value
}
// SetScore sets the score property value. The score property
func (m *UserActivity_tournaments_best) SetScore(value *int32)() {
    m.score = value
}
// SetTournament sets the tournament property value. The tournament property
func (m *UserActivity_tournaments_best) SetTournament(value UserActivity_tournaments_best_tournamentable)() {
    m.tournament = value
}
type UserActivity_tournaments_bestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetNbGames()(*int32)
    GetRank()(*int32)
    GetRankPercent()(*int32)
    GetScore()(*int32)
    GetTournament()(UserActivity_tournaments_best_tournamentable)
    SetNbGames(value *int32)()
    SetRank(value *int32)()
    SetRankPercent(value *int32)()
    SetScore(value *int32)()
    SetTournament(value UserActivity_tournaments_best_tournamentable)()
}
