// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type UserActivity_correspondenceEnds_correspondence struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The games property
    games []UserActivityCorrespondenceGameable
    // The score property
    score UserActivityScoreable
}
// NewUserActivity_correspondenceEnds_correspondence instantiates a new UserActivity_correspondenceEnds_correspondence and sets the default values.
func NewUserActivity_correspondenceEnds_correspondence()(*UserActivity_correspondenceEnds_correspondence) {
    m := &UserActivity_correspondenceEnds_correspondence{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateUserActivity_correspondenceEnds_correspondenceFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateUserActivity_correspondenceEnds_correspondenceFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewUserActivity_correspondenceEnds_correspondence(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *UserActivity_correspondenceEnds_correspondence) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *UserActivity_correspondenceEnds_correspondence) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["games"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateUserActivityCorrespondenceGameFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]UserActivityCorrespondenceGameable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(UserActivityCorrespondenceGameable)
                }
            }
            m.SetGames(res)
        }
        return nil
    }
    res["score"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateUserActivityScoreFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetScore(val.(UserActivityScoreable))
        }
        return nil
    }
    return res
}
// GetGames gets the games property value. The games property
// returns a []UserActivityCorrespondenceGameable when successful
func (m *UserActivity_correspondenceEnds_correspondence) GetGames()([]UserActivityCorrespondenceGameable) {
    return m.games
}
// GetScore gets the score property value. The score property
// returns a UserActivityScoreable when successful
func (m *UserActivity_correspondenceEnds_correspondence) GetScore()(UserActivityScoreable) {
    return m.score
}
// Serialize serializes information the current object
func (m *UserActivity_correspondenceEnds_correspondence) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetGames() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetGames()))
        for i, v := range m.GetGames() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("games", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("score", m.GetScore())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *UserActivity_correspondenceEnds_correspondence) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetGames sets the games property value. The games property
func (m *UserActivity_correspondenceEnds_correspondence) SetGames(value []UserActivityCorrespondenceGameable)() {
    m.games = value
}
// SetScore sets the score property value. The score property
func (m *UserActivity_correspondenceEnds_correspondence) SetScore(value UserActivityScoreable)() {
    m.score = value
}
type UserActivity_correspondenceEnds_correspondenceable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetGames()([]UserActivityCorrespondenceGameable)
    GetScore()(UserActivityScoreable)
    SetGames(value []UserActivityCorrespondenceGameable)()
    SetScore(value UserActivityScoreable)()
}
