// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type UserActivityCorrespondenceGame_opponentMember2 struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The rating property
	rating *int32
	// The user property
	user *string
}

// NewUserActivityCorrespondenceGame_opponentMember2 instantiates a new UserActivityCorrespondenceGame_opponentMember2 and sets the default values.
func NewUserActivityCorrespondenceGame_opponentMember2() *UserActivityCorrespondenceGame_opponentMember2 {
	m := &UserActivityCorrespondenceGame_opponentMember2{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateUserActivityCorrespondenceGame_opponentMember2FromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateUserActivityCorrespondenceGame_opponentMember2FromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewUserActivityCorrespondenceGame_opponentMember2(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *UserActivityCorrespondenceGame_opponentMember2) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *UserActivityCorrespondenceGame_opponentMember2) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["rating"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRating(val)
		}
		return nil
	}
	res["user"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUser(val)
		}
		return nil
	}
	return res
}

// GetRating gets the rating property value. The rating property
// returns a *int32 when successful
func (m *UserActivityCorrespondenceGame_opponentMember2) GetRating() *int32 {
	return m.rating
}

// GetUser gets the user property value. The user property
// returns a *string when successful
func (m *UserActivityCorrespondenceGame_opponentMember2) GetUser() *string {
	return m.user
}

// Serialize serializes information the current object
func (m *UserActivityCorrespondenceGame_opponentMember2) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt32Value("rating", m.GetRating())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("user", m.GetUser())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *UserActivityCorrespondenceGame_opponentMember2) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetRating sets the rating property value. The rating property
func (m *UserActivityCorrespondenceGame_opponentMember2) SetRating(value *int32) {
	m.rating = value
}

// SetUser sets the user property value. The user property
func (m *UserActivityCorrespondenceGame_opponentMember2) SetUser(value *string) {
	m.user = value
}

type UserActivityCorrespondenceGame_opponentMember2able interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetRating() *int32
	GetUser() *string
	SetRating(value *int32)
	SetUser(value *string)
}
