// Code generated by openapi-client-generator. DO NOT EDIT.

package openapi_client_generator

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
)

// Sentinel errors for common HTTP status codes. Use with errors.Is:
//
//	if errors.Is(err, ErrNotFound) { ... }
var (
	ErrBadRequest          = &APIError{StatusCode: http.StatusBadRequest}
	ErrUnauthorized        = &APIError{StatusCode: http.StatusUnauthorized}
	ErrForbidden           = &APIError{StatusCode: http.StatusForbidden}
	ErrNotFound            = &APIError{StatusCode: http.StatusNotFound}
	ErrConflict            = &APIError{StatusCode: http.StatusConflict}
	ErrTooManyRequests     = &APIError{StatusCode: http.StatusTooManyRequests}
	ErrInternalServerError = &APIError{StatusCode: http.StatusInternalServerError}
	ErrBadGateway          = &APIError{StatusCode: http.StatusBadGateway}
	ErrServiceUnavailable  = &APIError{StatusCode: http.StatusServiceUnavailable}
	ErrGatewayTimeout      = &APIError{StatusCode: http.StatusGatewayTimeout}
)

// APIError represents a non-2xx HTTP response.
type APIError struct {
	StatusCode int
	Status     string
	Body       []byte
}

func (e *APIError) Error() string {
	// Status already carries the code (e.g. "409 Conflict"); reconstruct it from StatusCode for the
	// sentinel errors, which set only StatusCode, so the code is never printed twice.
	status := e.Status
	if status == "" {
		if text := http.StatusText(e.StatusCode); text != "" {
			status = fmt.Sprintf("%d %s", e.StatusCode, text)
		} else {
			status = fmt.Sprintf("%d", e.StatusCode)
		}
	}
	if len(e.Body) > 0 {
		return fmt.Sprintf("API error %s: %s", status, e.Body)
	}
	return fmt.Sprintf("API error %s", status)
}

// Is supports errors.Is by matching on status code.
func (e *APIError) Is(target error) bool {
	t, ok := target.(*APIError)
	if !ok {
		return false
	}
	return e.StatusCode == t.StatusCode
}

// anyResponse wraps an APIError with a parsed any body.
type anyResponse struct {
	*APIError
	Detail any
}

func (e *anyResponse) Error() string {
	return e.APIError.Error()
}

func (e *anyResponse) Unwrap() error {
	return e.APIError
}

func parseanyResponse(err error) error {
	var apiErr *APIError
	if !errors.As(err, &apiErr) || len(apiErr.Body) == 0 {
		return err
	}
	resp := &anyResponse{APIError: apiErr}
	if json.Unmarshal(apiErr.Body, &resp.Detail) == nil {
		return resp
	}
	return err
}

// NotFoundResponse wraps an APIError with a parsed NotFound body.
type NotFoundResponse struct {
	*APIError
	Detail NotFound
}

func (e *NotFoundResponse) Error() string {
	return e.APIError.Error()
}

func (e *NotFoundResponse) Unwrap() error {
	return e.APIError
}

func parseNotFoundResponse(err error) error {
	var apiErr *APIError
	if !errors.As(err, &apiErr) || len(apiErr.Body) == 0 {
		return err
	}
	resp := &NotFoundResponse{APIError: apiErr}
	if json.Unmarshal(apiErr.Body, &resp.Detail) == nil {
		return resp
	}
	return err
}

// ErrorResponse wraps an APIError with a parsed Error body.
type ErrorResponse struct {
	*APIError
	Detail Error
}

func (e *ErrorResponse) Error() string {
	return e.APIError.Error()
}

func (e *ErrorResponse) Unwrap() error {
	return e.APIError
}

func parseErrorResponse(err error) error {
	var apiErr *APIError
	if !errors.As(err, &apiErr) || len(apiErr.Body) == 0 {
		return err
	}
	resp := &ErrorResponse{APIError: apiErr}
	if json.Unmarshal(apiErr.Body, &resp.Detail) == nil {
		return resp
	}
	return err
}

// SwissUnauthorisedEditResponse wraps an APIError with a parsed SwissUnauthorisedEdit body.
type SwissUnauthorisedEditResponse struct {
	*APIError
	Detail SwissUnauthorisedEdit
}

func (e *SwissUnauthorisedEditResponse) Error() string {
	return e.APIError.Error()
}

func (e *SwissUnauthorisedEditResponse) Unwrap() error {
	return e.APIError
}

func parseSwissUnauthorisedEditResponse(err error) error {
	var apiErr *APIError
	if !errors.As(err, &apiErr) || len(apiErr.Body) == 0 {
		return err
	}
	resp := &SwissUnauthorisedEditResponse{APIError: apiErr}
	if json.Unmarshal(apiErr.Body, &resp.Detail) == nil {
		return resp
	}
	return err
}

// OAuthErrorResponse wraps an APIError with a parsed OAuthError body.
type OAuthErrorResponse struct {
	*APIError
	Detail OAuthError
}

func (e *OAuthErrorResponse) Error() string {
	return e.APIError.Error()
}

func (e *OAuthErrorResponse) Unwrap() error {
	return e.APIError
}

func parseOAuthErrorResponse(err error) error {
	var apiErr *APIError
	if !errors.As(err, &apiErr) || len(apiErr.Body) == 0 {
		return err
	}
	resp := &OAuthErrorResponse{APIError: apiErr}
	if json.Unmarshal(apiErr.Body, &resp.Detail) == nil {
		return resp
	}
	return err
}
