// Code generated by openapi-client-generator. DO NOT EDIT.

package openapi_client_generator

import (
	"context"
	"net/http"
)

// ResponseMeta carries what a response says outside its body: the status it
// arrived with and the headers it carried.
type ResponseMeta struct {
	StatusCode int
	Status     string
	Header     http.Header
}

type responseCaptureKey struct{}

// WithResponseCapture returns a context that records what the next response says
// outside its body, and the ResponseMeta it lands in. Calls made with the
// returned context each overwrite it, so give one capture to one call.
//
//	ctx, meta := WithResponseCapture(ctx)
//	pet, err := client.GetPetByID(ctx, 123)
//	fmt.Println(meta.StatusCode, meta.Header.Get("X-Request-Id"))
//
// An error response is captured too, so the status and headers are readable
// whether or not the call succeeded.
func WithResponseCapture(ctx context.Context) (context.Context, *ResponseMeta) {
	meta := &ResponseMeta{}
	return context.WithValue(ctx, responseCaptureKey{}, meta), meta
}

// captureResponse records resp on the ResponseMeta the caller attached to ctx.
func captureResponse(ctx context.Context, resp *http.Response) {
	meta, ok := ctx.Value(responseCaptureKey{}).(*ResponseMeta)
	if !ok || resp == nil {
		return
	}
	meta.StatusCode = resp.StatusCode
	meta.Status = resp.Status
	meta.Header = resp.Header.Clone()
}

// APIUsersStatusHeaders holds the headers APIUsersStatus declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIUsersStatusHeaders struct {
	AccessControlAllowOrigin string
}

// APIUsersStatusHeaders reads the headers APIUsersStatus declares out of the captured
// response.
func (m *ResponseMeta) APIUsersStatusHeaders() APIUsersStatusHeaders {
	return APIUsersStatusHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// PlayerHeaders holds the headers Player declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PlayerHeaders struct {
	AccessControlAllowOrigin string
}

// PlayerHeaders reads the headers Player declares out of the captured
// response.
func (m *ResponseMeta) PlayerHeaders() PlayerHeaders {
	return PlayerHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// PlayerTopNbPerfTypeHeaders holds the headers PlayerTopNbPerfType declares. A header the spec
// types as something other than a string is nil when the response omits it.
type PlayerTopNbPerfTypeHeaders struct {
	AccessControlAllowOrigin string
}

// PlayerTopNbPerfTypeHeaders reads the headers PlayerTopNbPerfType declares out of the captured
// response.
func (m *ResponseMeta) PlayerTopNbPerfTypeHeaders() PlayerTopNbPerfTypeHeaders {
	return PlayerTopNbPerfTypeHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIUserHeaders holds the headers APIUser declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIUserHeaders struct {
	AccessControlAllowOrigin string
}

// APIUserHeaders reads the headers APIUser declares out of the captured
// response.
func (m *ResponseMeta) APIUserHeaders() APIUserHeaders {
	return APIUserHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIUserRatingHistoryHeaders holds the headers APIUserRatingHistory declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIUserRatingHistoryHeaders struct {
	AccessControlAllowOrigin string
}

// APIUserRatingHistoryHeaders reads the headers APIUserRatingHistory declares out of the captured
// response.
func (m *ResponseMeta) APIUserRatingHistoryHeaders() APIUserRatingHistoryHeaders {
	return APIUserRatingHistoryHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIUserPerfHeaders holds the headers APIUserPerf declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIUserPerfHeaders struct {
	AccessControlAllowOrigin string
}

// APIUserPerfHeaders reads the headers APIUserPerf declares out of the captured
// response.
func (m *ResponseMeta) APIUserPerfHeaders() APIUserPerfHeaders {
	return APIUserPerfHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIUserActivityHeaders holds the headers APIUserActivity declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIUserActivityHeaders struct {
	AccessControlAllowOrigin string
}

// APIUserActivityHeaders reads the headers APIUserActivity declares out of the captured
// response.
func (m *ResponseMeta) APIUserActivityHeaders() APIUserActivityHeaders {
	return APIUserActivityHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIPuzzleDailyHeaders holds the headers APIPuzzleDaily declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIPuzzleDailyHeaders struct {
	AccessControlAllowOrigin string
}

// APIPuzzleDailyHeaders reads the headers APIPuzzleDaily declares out of the captured
// response.
func (m *ResponseMeta) APIPuzzleDailyHeaders() APIPuzzleDailyHeaders {
	return APIPuzzleDailyHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIPuzzleIDHeaders holds the headers APIPuzzleID declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIPuzzleIDHeaders struct {
	AccessControlAllowOrigin string
}

// APIPuzzleIDHeaders reads the headers APIPuzzleID declares out of the captured
// response.
func (m *ResponseMeta) APIPuzzleIDHeaders() APIPuzzleIDHeaders {
	return APIPuzzleIDHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIPuzzleNextHeaders holds the headers APIPuzzleNext declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIPuzzleNextHeaders struct {
	AccessControlAllowOrigin string
}

// APIPuzzleNextHeaders reads the headers APIPuzzleNext declares out of the captured
// response.
func (m *ResponseMeta) APIPuzzleNextHeaders() APIPuzzleNextHeaders {
	return APIPuzzleNextHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIPuzzleBatchSelectHeaders holds the headers APIPuzzleBatchSelect declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIPuzzleBatchSelectHeaders struct {
	AccessControlAllowOrigin string
}

// APIPuzzleBatchSelectHeaders reads the headers APIPuzzleBatchSelect declares out of the captured
// response.
func (m *ResponseMeta) APIPuzzleBatchSelectHeaders() APIPuzzleBatchSelectHeaders {
	return APIPuzzleBatchSelectHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIPuzzleBatchSolveHeaders holds the headers APIPuzzleBatchSolve declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIPuzzleBatchSolveHeaders struct {
	AccessControlAllowOrigin string
}

// APIPuzzleBatchSolveHeaders reads the headers APIPuzzleBatchSolve declares out of the captured
// response.
func (m *ResponseMeta) APIPuzzleBatchSolveHeaders() APIPuzzleBatchSolveHeaders {
	return APIPuzzleBatchSolveHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIPuzzleActivityHeaders holds the headers APIPuzzleActivity declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIPuzzleActivityHeaders struct {
	AccessControlAllowOrigin string
}

// APIPuzzleActivityHeaders reads the headers APIPuzzleActivity declares out of the captured
// response.
func (m *ResponseMeta) APIPuzzleActivityHeaders() APIPuzzleActivityHeaders {
	return APIPuzzleActivityHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIPuzzleReplayHeaders holds the headers APIPuzzleReplay declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIPuzzleReplayHeaders struct {
	AccessControlAllowOrigin string
}

// APIPuzzleReplayHeaders reads the headers APIPuzzleReplay declares out of the captured
// response.
func (m *ResponseMeta) APIPuzzleReplayHeaders() APIPuzzleReplayHeaders {
	return APIPuzzleReplayHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIPuzzleDashboardHeaders holds the headers APIPuzzleDashboard declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIPuzzleDashboardHeaders struct {
	AccessControlAllowOrigin string
}

// APIPuzzleDashboardHeaders reads the headers APIPuzzleDashboard declares out of the captured
// response.
func (m *ResponseMeta) APIPuzzleDashboardHeaders() APIPuzzleDashboardHeaders {
	return APIPuzzleDashboardHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIStormDashboardHeaders holds the headers APIStormDashboard declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIStormDashboardHeaders struct {
	AccessControlAllowOrigin string
}

// APIStormDashboardHeaders reads the headers APIStormDashboard declares out of the captured
// response.
func (m *ResponseMeta) APIStormDashboardHeaders() APIStormDashboardHeaders {
	return APIStormDashboardHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// RacerPostHeaders holds the headers RacerPost declares. A header the spec
// types as something other than a string is nil when the response omits it.
type RacerPostHeaders struct {
	AccessControlAllowOrigin string
}

// RacerPostHeaders reads the headers RacerPost declares out of the captured
// response.
func (m *ResponseMeta) RacerPostHeaders() RacerPostHeaders {
	return RacerPostHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// RacerGetHeaders holds the headers RacerGet declares. A header the spec
// types as something other than a string is nil when the response omits it.
type RacerGetHeaders struct {
	AccessControlAllowOrigin string
}

// RacerGetHeaders reads the headers RacerGet declares out of the captured
// response.
func (m *ResponseMeta) RacerGetHeaders() RacerGetHeaders {
	return RacerGetHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIUsersHeaders holds the headers APIUsers declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIUsersHeaders struct {
	AccessControlAllowOrigin string
}

// APIUsersHeaders reads the headers APIUsers declares out of the captured
// response.
func (m *ResponseMeta) APIUsersHeaders() APIUsersHeaders {
	return APIUsersHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// AccountMeHeaders holds the headers AccountMe declares. A header the spec
// types as something other than a string is nil when the response omits it.
type AccountMeHeaders struct {
	AccessControlAllowOrigin string
}

// AccountMeHeaders reads the headers AccountMe declares out of the captured
// response.
func (m *ResponseMeta) AccountMeHeaders() AccountMeHeaders {
	return AccountMeHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// AccountEmailHeaders holds the headers AccountEmail declares. A header the spec
// types as something other than a string is nil when the response omits it.
type AccountEmailHeaders struct {
	AccessControlAllowOrigin string
}

// AccountEmailHeaders reads the headers AccountEmail declares out of the captured
// response.
func (m *ResponseMeta) AccountEmailHeaders() AccountEmailHeaders {
	return AccountEmailHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// AccountHeaders holds the headers Account declares. A header the spec
// types as something other than a string is nil when the response omits it.
type AccountHeaders struct {
	AccessControlAllowOrigin string
}

// AccountHeaders reads the headers Account declares out of the captured
// response.
func (m *ResponseMeta) AccountHeaders() AccountHeaders {
	return AccountHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// AccountKidHeaders holds the headers AccountKid declares. A header the spec
// types as something other than a string is nil when the response omits it.
type AccountKidHeaders struct {
	AccessControlAllowOrigin string
}

// AccountKidHeaders reads the headers AccountKid declares out of the captured
// response.
func (m *ResponseMeta) AccountKidHeaders() AccountKidHeaders {
	return AccountKidHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// AccountKidPostHeaders holds the headers AccountKidPost declares. A header the spec
// types as something other than a string is nil when the response omits it.
type AccountKidPostHeaders struct {
	AccessControlAllowOrigin string
}

// AccountKidPostHeaders reads the headers AccountKidPost declares out of the captured
// response.
func (m *ResponseMeta) AccountKidPostHeaders() AccountKidPostHeaders {
	return AccountKidPostHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TimelineHeaders holds the headers Timeline declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TimelineHeaders struct {
	AccessControlAllowOrigin string
}

// TimelineHeaders reads the headers Timeline declares out of the captured
// response.
func (m *ResponseMeta) TimelineHeaders() TimelineHeaders {
	return TimelineHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// GamePgnHeaders holds the headers GamePgn declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GamePgnHeaders struct {
	AccessControlAllowOrigin string
}

// GamePgnHeaders reads the headers GamePgn declares out of the captured
// response.
func (m *ResponseMeta) GamePgnHeaders() GamePgnHeaders {
	return GamePgnHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// GameChatGetHeaders holds the headers GameChatGet declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GameChatGetHeaders struct {
	AccessControlAllowOrigin string
}

// GameChatGetHeaders reads the headers GameChatGet declares out of the captured
// response.
func (m *ResponseMeta) GameChatGetHeaders() GameChatGetHeaders {
	return GameChatGetHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIUserCurrentGameHeaders holds the headers APIUserCurrentGame declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIUserCurrentGameHeaders struct {
	AccessControlAllowOrigin string
}

// APIUserCurrentGameHeaders reads the headers APIUserCurrentGame declares out of the captured
// response.
func (m *ResponseMeta) APIUserCurrentGameHeaders() APIUserCurrentGameHeaders {
	return APIUserCurrentGameHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIGamesUserHeaders holds the headers APIGamesUser declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIGamesUserHeaders struct {
	AccessControlAllowOrigin string
}

// APIGamesUserHeaders reads the headers APIGamesUser declares out of the captured
// response.
func (m *ResponseMeta) APIGamesUserHeaders() APIGamesUserHeaders {
	return APIGamesUserHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// GamesExportIdsHeaders holds the headers GamesExportIds declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GamesExportIdsHeaders struct {
	AccessControlAllowOrigin string
}

// GamesExportIdsHeaders reads the headers GamesExportIds declares out of the captured
// response.
func (m *ResponseMeta) GamesExportIdsHeaders() GamesExportIdsHeaders {
	return GamesExportIdsHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// GamesByUsersHeaders holds the headers GamesByUsers declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GamesByUsersHeaders struct {
	AccessControlAllowOrigin string
}

// GamesByUsersHeaders reads the headers GamesByUsers declares out of the captured
// response.
func (m *ResponseMeta) GamesByUsersHeaders() GamesByUsersHeaders {
	return GamesByUsersHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// GamesByIdsHeaders holds the headers GamesByIds declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GamesByIdsHeaders struct {
	AccessControlAllowOrigin string
}

// GamesByIdsHeaders reads the headers GamesByIds declares out of the captured
// response.
func (m *ResponseMeta) GamesByIdsHeaders() GamesByIdsHeaders {
	return GamesByIdsHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// GamesByIdsAddHeaders holds the headers GamesByIdsAdd declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GamesByIdsAddHeaders struct {
	AccessControlAllowOrigin string
}

// GamesByIdsAddHeaders reads the headers GamesByIdsAdd declares out of the captured
// response.
func (m *ResponseMeta) GamesByIdsAddHeaders() GamesByIdsAddHeaders {
	return GamesByIdsAddHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIAccountPlayingHeaders holds the headers APIAccountPlaying declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIAccountPlayingHeaders struct {
	AccessControlAllowOrigin string
}

// APIAccountPlayingHeaders reads the headers APIAccountPlaying declares out of the captured
// response.
func (m *ResponseMeta) APIAccountPlayingHeaders() APIAccountPlayingHeaders {
	return APIAccountPlayingHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// GameImportHeaders holds the headers GameImport declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GameImportHeaders struct {
	AccessControlAllowOrigin string
}

// GameImportHeaders reads the headers GameImport declares out of the captured
// response.
func (m *ResponseMeta) GameImportHeaders() GameImportHeaders {
	return GameImportHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIImportedGamesUserHeaders holds the headers APIImportedGamesUser declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIImportedGamesUserHeaders struct {
	AccessControlAllowOrigin string
}

// APIImportedGamesUserHeaders reads the headers APIImportedGamesUser declares out of the captured
// response.
func (m *ResponseMeta) APIImportedGamesUserHeaders() APIImportedGamesUserHeaders {
	return APIImportedGamesUserHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIExportBookmarksHeaders holds the headers APIExportBookmarks declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIExportBookmarksHeaders struct {
	AccessControlAllowOrigin string
}

// APIExportBookmarksHeaders reads the headers APIExportBookmarks declares out of the captured
// response.
func (m *ResponseMeta) APIExportBookmarksHeaders() APIExportBookmarksHeaders {
	return APIExportBookmarksHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BookmarkToggleHeaders holds the headers BookmarkToggle declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BookmarkToggleHeaders struct {
	AccessControlAllowOrigin string
}

// BookmarkToggleHeaders reads the headers BookmarkToggle declares out of the captured
// response.
func (m *ResponseMeta) BookmarkToggleHeaders() BookmarkToggleHeaders {
	return BookmarkToggleHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TvChannelsHeaders holds the headers TvChannels declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TvChannelsHeaders struct {
	AccessControlAllowOrigin string
}

// TvChannelsHeaders reads the headers TvChannels declares out of the captured
// response.
func (m *ResponseMeta) TvChannelsHeaders() TvChannelsHeaders {
	return TvChannelsHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APITournamentHeaders holds the headers APITournament declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APITournamentHeaders struct {
	AccessControlAllowOrigin string
}

// APITournamentHeaders reads the headers APITournament declares out of the captured
// response.
func (m *ResponseMeta) APITournamentHeaders() APITournamentHeaders {
	return APITournamentHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APITournamentPostHeaders holds the headers APITournamentPost declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APITournamentPostHeaders struct {
	AccessControlAllowOrigin string
}

// APITournamentPostHeaders reads the headers APITournamentPost declares out of the captured
// response.
func (m *ResponseMeta) APITournamentPostHeaders() APITournamentPostHeaders {
	return APITournamentPostHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TournamentHeaders holds the headers Tournament declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TournamentHeaders struct {
	AccessControlAllowOrigin string
}

// TournamentHeaders reads the headers Tournament declares out of the captured
// response.
func (m *ResponseMeta) TournamentHeaders() TournamentHeaders {
	return TournamentHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APITournamentUpdateHeaders holds the headers APITournamentUpdate declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APITournamentUpdateHeaders struct {
	AccessControlAllowOrigin string
}

// APITournamentUpdateHeaders reads the headers APITournamentUpdate declares out of the captured
// response.
func (m *ResponseMeta) APITournamentUpdateHeaders() APITournamentUpdateHeaders {
	return APITournamentUpdateHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APITournamentJoinHeaders holds the headers APITournamentJoin declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APITournamentJoinHeaders struct {
	AccessControlAllowOrigin string
}

// APITournamentJoinHeaders reads the headers APITournamentJoin declares out of the captured
// response.
func (m *ResponseMeta) APITournamentJoinHeaders() APITournamentJoinHeaders {
	return APITournamentJoinHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APITournamentWithdrawHeaders holds the headers APITournamentWithdraw declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APITournamentWithdrawHeaders struct {
	AccessControlAllowOrigin string
}

// APITournamentWithdrawHeaders reads the headers APITournamentWithdraw declares out of the captured
// response.
func (m *ResponseMeta) APITournamentWithdrawHeaders() APITournamentWithdrawHeaders {
	return APITournamentWithdrawHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APITournamentTerminateHeaders holds the headers APITournamentTerminate declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APITournamentTerminateHeaders struct {
	AccessControlAllowOrigin string
}

// APITournamentTerminateHeaders reads the headers APITournamentTerminate declares out of the captured
// response.
func (m *ResponseMeta) APITournamentTerminateHeaders() APITournamentTerminateHeaders {
	return APITournamentTerminateHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APITournamentTeamBattlePostHeaders holds the headers APITournamentTeamBattlePost declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APITournamentTeamBattlePostHeaders struct {
	AccessControlAllowOrigin string
}

// APITournamentTeamBattlePostHeaders reads the headers APITournamentTeamBattlePost declares out of the captured
// response.
func (m *ResponseMeta) APITournamentTeamBattlePostHeaders() APITournamentTeamBattlePostHeaders {
	return APITournamentTeamBattlePostHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// GamesByTournamentHeaders holds the headers GamesByTournament declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GamesByTournamentHeaders struct {
	AccessControlAllowOrigin string
}

// GamesByTournamentHeaders reads the headers GamesByTournament declares out of the captured
// response.
func (m *ResponseMeta) GamesByTournamentHeaders() GamesByTournamentHeaders {
	return GamesByTournamentHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// ResultsByTournamentHeaders holds the headers ResultsByTournament declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ResultsByTournamentHeaders struct {
	AccessControlAllowOrigin string
}

// ResultsByTournamentHeaders reads the headers ResultsByTournament declares out of the captured
// response.
func (m *ResponseMeta) ResultsByTournamentHeaders() ResultsByTournamentHeaders {
	return ResultsByTournamentHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TeamsByTournamentHeaders holds the headers TeamsByTournament declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TeamsByTournamentHeaders struct {
	AccessControlAllowOrigin string
}

// TeamsByTournamentHeaders reads the headers TeamsByTournament declares out of the captured
// response.
func (m *ResponseMeta) TeamsByTournamentHeaders() TeamsByTournamentHeaders {
	return TeamsByTournamentHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIUserNameTournamentCreatedHeaders holds the headers APIUserNameTournamentCreated declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIUserNameTournamentCreatedHeaders struct {
	AccessControlAllowOrigin string
}

// APIUserNameTournamentCreatedHeaders reads the headers APIUserNameTournamentCreated declares out of the captured
// response.
func (m *ResponseMeta) APIUserNameTournamentCreatedHeaders() APIUserNameTournamentCreatedHeaders {
	return APIUserNameTournamentCreatedHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIUserNameTournamentPlayedHeaders holds the headers APIUserNameTournamentPlayed declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIUserNameTournamentPlayedHeaders struct {
	AccessControlAllowOrigin string
}

// APIUserNameTournamentPlayedHeaders reads the headers APIUserNameTournamentPlayed declares out of the captured
// response.
func (m *ResponseMeta) APIUserNameTournamentPlayedHeaders() APIUserNameTournamentPlayedHeaders {
	return APIUserNameTournamentPlayedHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APISwissNewHeaders holds the headers APISwissNew declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APISwissNewHeaders struct {
	AccessControlAllowOrigin string
}

// APISwissNewHeaders reads the headers APISwissNew declares out of the captured
// response.
func (m *ResponseMeta) APISwissNewHeaders() APISwissNewHeaders {
	return APISwissNewHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// SwissHeaders holds the headers Swiss declares. A header the spec
// types as something other than a string is nil when the response omits it.
type SwissHeaders struct {
	AccessControlAllowOrigin string
}

// SwissHeaders reads the headers Swiss declares out of the captured
// response.
func (m *ResponseMeta) SwissHeaders() SwissHeaders {
	return SwissHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APISwissUpdateHeaders holds the headers APISwissUpdate declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APISwissUpdateHeaders struct {
	AccessControlAllowOrigin string
}

// APISwissUpdateHeaders reads the headers APISwissUpdate declares out of the captured
// response.
func (m *ResponseMeta) APISwissUpdateHeaders() APISwissUpdateHeaders {
	return APISwissUpdateHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APISwissScheduleNextRoundHeaders holds the headers APISwissScheduleNextRound declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APISwissScheduleNextRoundHeaders struct {
	AccessControlAllowOrigin string
}

// APISwissScheduleNextRoundHeaders reads the headers APISwissScheduleNextRound declares out of the captured
// response.
func (m *ResponseMeta) APISwissScheduleNextRoundHeaders() APISwissScheduleNextRoundHeaders {
	return APISwissScheduleNextRoundHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APISwissJoinHeaders holds the headers APISwissJoin declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APISwissJoinHeaders struct {
	AccessControlAllowOrigin string
}

// APISwissJoinHeaders reads the headers APISwissJoin declares out of the captured
// response.
func (m *ResponseMeta) APISwissJoinHeaders() APISwissJoinHeaders {
	return APISwissJoinHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APISwissWithdrawHeaders holds the headers APISwissWithdraw declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APISwissWithdrawHeaders struct {
	AccessControlAllowOrigin string
}

// APISwissWithdrawHeaders reads the headers APISwissWithdraw declares out of the captured
// response.
func (m *ResponseMeta) APISwissWithdrawHeaders() APISwissWithdrawHeaders {
	return APISwissWithdrawHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APISwissTerminateHeaders holds the headers APISwissTerminate declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APISwissTerminateHeaders struct {
	AccessControlAllowOrigin string
}

// APISwissTerminateHeaders reads the headers APISwissTerminate declares out of the captured
// response.
func (m *ResponseMeta) APISwissTerminateHeaders() APISwissTerminateHeaders {
	return APISwissTerminateHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// SwissTrfHeaders holds the headers SwissTrf declares. A header the spec
// types as something other than a string is nil when the response omits it.
type SwissTrfHeaders struct {
	AccessControlAllowOrigin string
}

// SwissTrfHeaders reads the headers SwissTrf declares out of the captured
// response.
func (m *ResponseMeta) SwissTrfHeaders() SwissTrfHeaders {
	return SwissTrfHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// GamesBySwissHeaders holds the headers GamesBySwiss declares. A header the spec
// types as something other than a string is nil when the response omits it.
type GamesBySwissHeaders struct {
	AccessControlAllowOrigin string
}

// GamesBySwissHeaders reads the headers GamesBySwiss declares out of the captured
// response.
func (m *ResponseMeta) GamesBySwissHeaders() GamesBySwissHeaders {
	return GamesBySwissHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// ResultsBySwissHeaders holds the headers ResultsBySwiss declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ResultsBySwissHeaders struct {
	AccessControlAllowOrigin string
}

// ResultsBySwissHeaders reads the headers ResultsBySwiss declares out of the captured
// response.
func (m *ResponseMeta) ResultsBySwissHeaders() ResultsBySwissHeaders {
	return ResultsBySwissHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APITeamSwissHeaders holds the headers APITeamSwiss declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APITeamSwissHeaders struct {
	AccessControlAllowOrigin string
}

// APITeamSwissHeaders reads the headers APITeamSwiss declares out of the captured
// response.
func (m *ResponseMeta) APITeamSwissHeaders() APITeamSwissHeaders {
	return APITeamSwissHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// StudyAllChaptersPgnHeaders holds the headers StudyAllChaptersPgn declares. A header the spec
// types as something other than a string is nil when the response omits it.
type StudyAllChaptersPgnHeaders struct {
	AccessControlAllowOrigin string
	LastModified             string
}

// StudyAllChaptersPgnHeaders reads the headers StudyAllChaptersPgn declares out of the captured
// response.
func (m *ResponseMeta) StudyAllChaptersPgnHeaders() StudyAllChaptersPgnHeaders {
	return StudyAllChaptersPgnHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
		LastModified:             m.Header.Get("Last-Modified"),
	}
}

// StudyAllChaptersHeadHeaders holds the headers StudyAllChaptersHead declares. A header the spec
// types as something other than a string is nil when the response omits it.
type StudyAllChaptersHeadHeaders struct {
	AccessControlAllowOrigin string
	LastModified             string
}

// StudyAllChaptersHeadHeaders reads the headers StudyAllChaptersHead declares out of the captured
// response.
func (m *ResponseMeta) StudyAllChaptersHeadHeaders() StudyAllChaptersHeadHeaders {
	return StudyAllChaptersHeadHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
		LastModified:             m.Header.Get("Last-Modified"),
	}
}

// APIStudyPostHeaders holds the headers APIStudyPost declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIStudyPostHeaders struct {
	AccessControlAllowOrigin string
}

// APIStudyPostHeaders reads the headers APIStudyPost declares out of the captured
// response.
func (m *ResponseMeta) APIStudyPostHeaders() APIStudyPostHeaders {
	return APIStudyPostHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIStudyImportPgnHeaders holds the headers APIStudyImportPgn declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIStudyImportPgnHeaders struct {
	AccessControlAllowOrigin string
}

// APIStudyImportPgnHeaders reads the headers APIStudyImportPgn declares out of the captured
// response.
func (m *ResponseMeta) APIStudyImportPgnHeaders() APIStudyImportPgnHeaders {
	return APIStudyImportPgnHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIStudyChapterTagsHeaders holds the headers APIStudyChapterTags declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIStudyChapterTagsHeaders struct {
	AccessControlAllowOrigin string
}

// APIStudyChapterTagsHeaders reads the headers APIStudyChapterTags declares out of the captured
// response.
func (m *ResponseMeta) APIStudyChapterTagsHeaders() APIStudyChapterTagsHeaders {
	return APIStudyChapterTagsHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIStudyChapterMovesHeaders holds the headers APIStudyChapterMoves declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIStudyChapterMovesHeaders struct {
	AccessControlAllowOrigin string
}

// APIStudyChapterMovesHeaders reads the headers APIStudyChapterMoves declares out of the captured
// response.
func (m *ResponseMeta) APIStudyChapterMovesHeaders() APIStudyChapterMovesHeaders {
	return APIStudyChapterMovesHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// StudyListMetadataHeaders holds the headers StudyListMetadata declares. A header the spec
// types as something other than a string is nil when the response omits it.
type StudyListMetadataHeaders struct {
	AccessControlAllowOrigin string
}

// StudyListMetadataHeaders reads the headers StudyListMetadata declares out of the captured
// response.
func (m *ResponseMeta) StudyListMetadataHeaders() StudyListMetadataHeaders {
	return StudyListMetadataHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIStudyStudyIDChapterIDDeleteHeaders holds the headers APIStudyStudyIDChapterIDDelete declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIStudyStudyIDChapterIDDeleteHeaders struct {
	AccessControlAllowOrigin string
}

// APIStudyStudyIDChapterIDDeleteHeaders reads the headers APIStudyStudyIDChapterIDDelete declares out of the captured
// response.
func (m *ResponseMeta) APIStudyStudyIDChapterIDDeleteHeaders() APIStudyStudyIDChapterIDDeleteHeaders {
	return APIStudyStudyIDChapterIDDeleteHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastsOfficialHeaders holds the headers BroadcastsOfficial declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastsOfficialHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastsOfficialHeaders reads the headers BroadcastsOfficial declares out of the captured
// response.
func (m *ResponseMeta) BroadcastsOfficialHeaders() BroadcastsOfficialHeaders {
	return BroadcastsOfficialHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastsTopHeaders holds the headers BroadcastsTop declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastsTopHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastsTopHeaders reads the headers BroadcastsTop declares out of the captured
// response.
func (m *ResponseMeta) BroadcastsTopHeaders() BroadcastsTopHeaders {
	return BroadcastsTopHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastsByUserHeaders holds the headers BroadcastsByUser declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastsByUserHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastsByUserHeaders reads the headers BroadcastsByUser declares out of the captured
// response.
func (m *ResponseMeta) BroadcastsByUserHeaders() BroadcastsByUserHeaders {
	return BroadcastsByUserHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastsSearchHeaders holds the headers BroadcastsSearch declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastsSearchHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastsSearchHeaders reads the headers BroadcastsSearch declares out of the captured
// response.
func (m *ResponseMeta) BroadcastsSearchHeaders() BroadcastsSearchHeaders {
	return BroadcastsSearchHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastTourCreateHeaders holds the headers BroadcastTourCreate declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastTourCreateHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastTourCreateHeaders reads the headers BroadcastTourCreate declares out of the captured
// response.
func (m *ResponseMeta) BroadcastTourCreateHeaders() BroadcastTourCreateHeaders {
	return BroadcastTourCreateHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastTourUpdateHeaders holds the headers BroadcastTourUpdate declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastTourUpdateHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastTourUpdateHeaders reads the headers BroadcastTourUpdate declares out of the captured
// response.
func (m *ResponseMeta) BroadcastTourUpdateHeaders() BroadcastTourUpdateHeaders {
	return BroadcastTourUpdateHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastRoundCreateHeaders holds the headers BroadcastRoundCreate declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastRoundCreateHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastRoundCreateHeaders reads the headers BroadcastRoundCreate declares out of the captured
// response.
func (m *ResponseMeta) BroadcastRoundCreateHeaders() BroadcastRoundCreateHeaders {
	return BroadcastRoundCreateHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastRoundUpdateHeaders holds the headers BroadcastRoundUpdate declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastRoundUpdateHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastRoundUpdateHeaders reads the headers BroadcastRoundUpdate declares out of the captured
// response.
func (m *ResponseMeta) BroadcastRoundUpdateHeaders() BroadcastRoundUpdateHeaders {
	return BroadcastRoundUpdateHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastRoundResetHeaders holds the headers BroadcastRoundReset declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastRoundResetHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastRoundResetHeaders reads the headers BroadcastRoundReset declares out of the captured
// response.
func (m *ResponseMeta) BroadcastRoundResetHeaders() BroadcastRoundResetHeaders {
	return BroadcastRoundResetHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastPushHeaders holds the headers BroadcastPush declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastPushHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastPushHeaders reads the headers BroadcastPush declares out of the captured
// response.
func (m *ResponseMeta) BroadcastPushHeaders() BroadcastPushHeaders {
	return BroadcastPushHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastStreamRoundPgnHeaders holds the headers BroadcastStreamRoundPgn declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastStreamRoundPgnHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastStreamRoundPgnHeaders reads the headers BroadcastStreamRoundPgn declares out of the captured
// response.
func (m *ResponseMeta) BroadcastStreamRoundPgnHeaders() BroadcastStreamRoundPgnHeaders {
	return BroadcastStreamRoundPgnHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastStreamTourPgnHeaders holds the headers BroadcastStreamTourPgn declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastStreamTourPgnHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastStreamTourPgnHeaders reads the headers BroadcastStreamTourPgn declares out of the captured
// response.
func (m *ResponseMeta) BroadcastStreamTourPgnHeaders() BroadcastStreamTourPgnHeaders {
	return BroadcastStreamTourPgnHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastStreamGroupPgnHeaders holds the headers BroadcastStreamGroupPgn declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastStreamGroupPgnHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastStreamGroupPgnHeaders reads the headers BroadcastStreamGroupPgn declares out of the captured
// response.
func (m *ResponseMeta) BroadcastStreamGroupPgnHeaders() BroadcastStreamGroupPgnHeaders {
	return BroadcastStreamGroupPgnHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastRoundPgnHeaders holds the headers BroadcastRoundPgn declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastRoundPgnHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastRoundPgnHeaders reads the headers BroadcastRoundPgn declares out of the captured
// response.
func (m *ResponseMeta) BroadcastRoundPgnHeaders() BroadcastRoundPgnHeaders {
	return BroadcastRoundPgnHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BroadcastAllRoundsPgnHeaders holds the headers BroadcastAllRoundsPgn declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BroadcastAllRoundsPgnHeaders struct {
	AccessControlAllowOrigin string
}

// BroadcastAllRoundsPgnHeaders reads the headers BroadcastAllRoundsPgn declares out of the captured
// response.
func (m *ResponseMeta) BroadcastAllRoundsPgnHeaders() BroadcastAllRoundsPgnHeaders {
	return BroadcastAllRoundsPgnHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// FidePlayerSearchHeaders holds the headers FidePlayerSearch declares. A header the spec
// types as something other than a string is nil when the response omits it.
type FidePlayerSearchHeaders struct {
	AccessControlAllowOrigin string
}

// FidePlayerSearchHeaders reads the headers FidePlayerSearch declares out of the captured
// response.
func (m *ResponseMeta) FidePlayerSearchHeaders() FidePlayerSearchHeaders {
	return FidePlayerSearchHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APISimulHeaders holds the headers APISimul declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APISimulHeaders struct {
	AccessControlAllowOrigin string
}

// APISimulHeaders reads the headers APISimul declares out of the captured
// response.
func (m *ResponseMeta) APISimulHeaders() APISimulHeaders {
	return APISimulHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TeamShowHeaders holds the headers TeamShow declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TeamShowHeaders struct {
	AccessControlAllowOrigin string
}

// TeamShowHeaders reads the headers TeamShow declares out of the captured
// response.
func (m *ResponseMeta) TeamShowHeaders() TeamShowHeaders {
	return TeamShowHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TeamAllHeaders holds the headers TeamAll declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TeamAllHeaders struct {
	AccessControlAllowOrigin string
}

// TeamAllHeaders reads the headers TeamAll declares out of the captured
// response.
func (m *ResponseMeta) TeamAllHeaders() TeamAllHeaders {
	return TeamAllHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TeamOfUsernameHeaders holds the headers TeamOfUsername declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TeamOfUsernameHeaders struct {
	AccessControlAllowOrigin string
}

// TeamOfUsernameHeaders reads the headers TeamOfUsername declares out of the captured
// response.
func (m *ResponseMeta) TeamOfUsernameHeaders() TeamOfUsernameHeaders {
	return TeamOfUsernameHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TeamSearchHeaders holds the headers TeamSearch declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TeamSearchHeaders struct {
	AccessControlAllowOrigin string
}

// TeamSearchHeaders reads the headers TeamSearch declares out of the captured
// response.
func (m *ResponseMeta) TeamSearchHeaders() TeamSearchHeaders {
	return TeamSearchHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TeamIDUsersHeaders holds the headers TeamIDUsers declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TeamIDUsersHeaders struct {
	AccessControlAllowOrigin string
}

// TeamIDUsersHeaders reads the headers TeamIDUsers declares out of the captured
// response.
func (m *ResponseMeta) TeamIDUsersHeaders() TeamIDUsersHeaders {
	return TeamIDUsersHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APITeamArenaHeaders holds the headers APITeamArena declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APITeamArenaHeaders struct {
	AccessControlAllowOrigin string
}

// APITeamArenaHeaders reads the headers APITeamArena declares out of the captured
// response.
func (m *ResponseMeta) APITeamArenaHeaders() APITeamArenaHeaders {
	return APITeamArenaHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TeamUpdatesHeaders holds the headers TeamUpdates declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TeamUpdatesHeaders struct {
	AccessControlAllowOrigin string
}

// TeamUpdatesHeaders reads the headers TeamUpdates declares out of the captured
// response.
func (m *ResponseMeta) TeamUpdatesHeaders() TeamUpdatesHeaders {
	return TeamUpdatesHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TeamUpdatesByTeamIDHeaders holds the headers TeamUpdatesByTeamID declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TeamUpdatesByTeamIDHeaders struct {
	AccessControlAllowOrigin string
}

// TeamUpdatesByTeamIDHeaders reads the headers TeamUpdatesByTeamID declares out of the captured
// response.
func (m *ResponseMeta) TeamUpdatesByTeamIDHeaders() TeamUpdatesByTeamIDHeaders {
	return TeamUpdatesByTeamIDHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TeamIDPmAllHeaders holds the headers TeamIDPmAll declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TeamIDPmAllHeaders struct {
	AccessControlAllowOrigin string
}

// TeamIDPmAllHeaders reads the headers TeamIDPmAll declares out of the captured
// response.
func (m *ResponseMeta) TeamIDPmAllHeaders() TeamIDPmAllHeaders {
	return TeamIDPmAllHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// StreamerLiveHeaders holds the headers StreamerLive declares. A header the spec
// types as something other than a string is nil when the response omits it.
type StreamerLiveHeaders struct {
	AccessControlAllowOrigin string
}

// StreamerLiveHeaders reads the headers StreamerLive declares out of the captured
// response.
func (m *ResponseMeta) StreamerLiveHeaders() StreamerLiveHeaders {
	return StreamerLiveHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APICrosstableHeaders holds the headers APICrosstable declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APICrosstableHeaders struct {
	AccessControlAllowOrigin string
}

// APICrosstableHeaders reads the headers APICrosstable declares out of the captured
// response.
func (m *ResponseMeta) APICrosstableHeaders() APICrosstableHeaders {
	return APICrosstableHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIPlayerAutocompleteHeaders holds the headers APIPlayerAutocomplete declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIPlayerAutocompleteHeaders struct {
	AccessControlAllowOrigin string
}

// APIPlayerAutocompleteHeaders reads the headers APIPlayerAutocomplete declares out of the captured
// response.
func (m *ResponseMeta) APIPlayerAutocompleteHeaders() APIPlayerAutocompleteHeaders {
	return APIPlayerAutocompleteHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// ReadNoteHeaders holds the headers ReadNote declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ReadNoteHeaders struct {
	AccessControlAllowOrigin string
}

// ReadNoteHeaders reads the headers ReadNote declares out of the captured
// response.
func (m *ResponseMeta) ReadNoteHeaders() ReadNoteHeaders {
	return ReadNoteHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIUserFollowingHeaders holds the headers APIUserFollowing declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIUserFollowingHeaders struct {
	AccessControlAllowOrigin string
}

// APIUserFollowingHeaders reads the headers APIUserFollowing declares out of the captured
// response.
func (m *ResponseMeta) APIUserFollowingHeaders() APIUserFollowingHeaders {
	return APIUserFollowingHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIStreamEventHeaders holds the headers APIStreamEvent declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIStreamEventHeaders struct {
	AccessControlAllowOrigin string
}

// APIStreamEventHeaders reads the headers APIStreamEvent declares out of the captured
// response.
func (m *ResponseMeta) APIStreamEventHeaders() APIStreamEventHeaders {
	return APIStreamEventHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIBoardSeekHeaders holds the headers APIBoardSeek declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIBoardSeekHeaders struct {
	AccessControlAllowOrigin string
}

// APIBoardSeekHeaders reads the headers APIBoardSeek declares out of the captured
// response.
func (m *ResponseMeta) APIBoardSeekHeaders() APIBoardSeekHeaders {
	return APIBoardSeekHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BoardGameStreamHeaders holds the headers BoardGameStream declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BoardGameStreamHeaders struct {
	AccessControlAllowOrigin string
}

// BoardGameStreamHeaders reads the headers BoardGameStream declares out of the captured
// response.
func (m *ResponseMeta) BoardGameStreamHeaders() BoardGameStreamHeaders {
	return BoardGameStreamHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BoardGameMoveHeaders holds the headers BoardGameMove declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BoardGameMoveHeaders struct {
	AccessControlAllowOrigin string
}

// BoardGameMoveHeaders reads the headers BoardGameMove declares out of the captured
// response.
func (m *ResponseMeta) BoardGameMoveHeaders() BoardGameMoveHeaders {
	return BoardGameMoveHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BoardGameChatGetHeaders holds the headers BoardGameChatGet declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BoardGameChatGetHeaders struct {
	AccessControlAllowOrigin string
}

// BoardGameChatGetHeaders reads the headers BoardGameChatGet declares out of the captured
// response.
func (m *ResponseMeta) BoardGameChatGetHeaders() BoardGameChatGetHeaders {
	return BoardGameChatGetHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BoardGameChatPostHeaders holds the headers BoardGameChatPost declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BoardGameChatPostHeaders struct {
	AccessControlAllowOrigin string
}

// BoardGameChatPostHeaders reads the headers BoardGameChatPost declares out of the captured
// response.
func (m *ResponseMeta) BoardGameChatPostHeaders() BoardGameChatPostHeaders {
	return BoardGameChatPostHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BoardGameAbortHeaders holds the headers BoardGameAbort declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BoardGameAbortHeaders struct {
	AccessControlAllowOrigin string
}

// BoardGameAbortHeaders reads the headers BoardGameAbort declares out of the captured
// response.
func (m *ResponseMeta) BoardGameAbortHeaders() BoardGameAbortHeaders {
	return BoardGameAbortHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BoardGameResignHeaders holds the headers BoardGameResign declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BoardGameResignHeaders struct {
	AccessControlAllowOrigin string
}

// BoardGameResignHeaders reads the headers BoardGameResign declares out of the captured
// response.
func (m *ResponseMeta) BoardGameResignHeaders() BoardGameResignHeaders {
	return BoardGameResignHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BoardGameDrawHeaders holds the headers BoardGameDraw declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BoardGameDrawHeaders struct {
	AccessControlAllowOrigin string
}

// BoardGameDrawHeaders reads the headers BoardGameDraw declares out of the captured
// response.
func (m *ResponseMeta) BoardGameDrawHeaders() BoardGameDrawHeaders {
	return BoardGameDrawHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BoardGameTakebackHeaders holds the headers BoardGameTakeback declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BoardGameTakebackHeaders struct {
	AccessControlAllowOrigin string
}

// BoardGameTakebackHeaders reads the headers BoardGameTakeback declares out of the captured
// response.
func (m *ResponseMeta) BoardGameTakebackHeaders() BoardGameTakebackHeaders {
	return BoardGameTakebackHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BoardGameClaimVictoryHeaders holds the headers BoardGameClaimVictory declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BoardGameClaimVictoryHeaders struct {
	AccessControlAllowOrigin string
}

// BoardGameClaimVictoryHeaders reads the headers BoardGameClaimVictory declares out of the captured
// response.
func (m *ResponseMeta) BoardGameClaimVictoryHeaders() BoardGameClaimVictoryHeaders {
	return BoardGameClaimVictoryHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BoardGameClaimDrawHeaders holds the headers BoardGameClaimDraw declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BoardGameClaimDrawHeaders struct {
	AccessControlAllowOrigin string
}

// BoardGameClaimDrawHeaders reads the headers BoardGameClaimDraw declares out of the captured
// response.
func (m *ResponseMeta) BoardGameClaimDrawHeaders() BoardGameClaimDrawHeaders {
	return BoardGameClaimDrawHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BoardGameBerserkHeaders holds the headers BoardGameBerserk declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BoardGameBerserkHeaders struct {
	AccessControlAllowOrigin string
}

// BoardGameBerserkHeaders reads the headers BoardGameBerserk declares out of the captured
// response.
func (m *ResponseMeta) BoardGameBerserkHeaders() BoardGameBerserkHeaders {
	return BoardGameBerserkHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIBotOnlineHeaders holds the headers APIBotOnline declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIBotOnlineHeaders struct {
	AccessControlAllowOrigin string
}

// APIBotOnlineHeaders reads the headers APIBotOnline declares out of the captured
// response.
func (m *ResponseMeta) APIBotOnlineHeaders() APIBotOnlineHeaders {
	return APIBotOnlineHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BotAccountUpgradeHeaders holds the headers BotAccountUpgrade declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BotAccountUpgradeHeaders struct {
	AccessControlAllowOrigin string
}

// BotAccountUpgradeHeaders reads the headers BotAccountUpgrade declares out of the captured
// response.
func (m *ResponseMeta) BotAccountUpgradeHeaders() BotAccountUpgradeHeaders {
	return BotAccountUpgradeHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BotGameStreamHeaders holds the headers BotGameStream declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BotGameStreamHeaders struct {
	AccessControlAllowOrigin string
}

// BotGameStreamHeaders reads the headers BotGameStream declares out of the captured
// response.
func (m *ResponseMeta) BotGameStreamHeaders() BotGameStreamHeaders {
	return BotGameStreamHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BotGameMoveHeaders holds the headers BotGameMove declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BotGameMoveHeaders struct {
	AccessControlAllowOrigin string
}

// BotGameMoveHeaders reads the headers BotGameMove declares out of the captured
// response.
func (m *ResponseMeta) BotGameMoveHeaders() BotGameMoveHeaders {
	return BotGameMoveHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BotGameChatGetHeaders holds the headers BotGameChatGet declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BotGameChatGetHeaders struct {
	AccessControlAllowOrigin string
}

// BotGameChatGetHeaders reads the headers BotGameChatGet declares out of the captured
// response.
func (m *ResponseMeta) BotGameChatGetHeaders() BotGameChatGetHeaders {
	return BotGameChatGetHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BotGameChatHeaders holds the headers BotGameChat declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BotGameChatHeaders struct {
	AccessControlAllowOrigin string
}

// BotGameChatHeaders reads the headers BotGameChat declares out of the captured
// response.
func (m *ResponseMeta) BotGameChatHeaders() BotGameChatHeaders {
	return BotGameChatHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BotGameAbortHeaders holds the headers BotGameAbort declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BotGameAbortHeaders struct {
	AccessControlAllowOrigin string
}

// BotGameAbortHeaders reads the headers BotGameAbort declares out of the captured
// response.
func (m *ResponseMeta) BotGameAbortHeaders() BotGameAbortHeaders {
	return BotGameAbortHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BotGameResignHeaders holds the headers BotGameResign declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BotGameResignHeaders struct {
	AccessControlAllowOrigin string
}

// BotGameResignHeaders reads the headers BotGameResign declares out of the captured
// response.
func (m *ResponseMeta) BotGameResignHeaders() BotGameResignHeaders {
	return BotGameResignHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BotGameDrawHeaders holds the headers BotGameDraw declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BotGameDrawHeaders struct {
	AccessControlAllowOrigin string
}

// BotGameDrawHeaders reads the headers BotGameDraw declares out of the captured
// response.
func (m *ResponseMeta) BotGameDrawHeaders() BotGameDrawHeaders {
	return BotGameDrawHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BotGameTakebackHeaders holds the headers BotGameTakeback declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BotGameTakebackHeaders struct {
	AccessControlAllowOrigin string
}

// BotGameTakebackHeaders reads the headers BotGameTakeback declares out of the captured
// response.
func (m *ResponseMeta) BotGameTakebackHeaders() BotGameTakebackHeaders {
	return BotGameTakebackHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BotGameClaimVictoryHeaders holds the headers BotGameClaimVictory declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BotGameClaimVictoryHeaders struct {
	AccessControlAllowOrigin string
}

// BotGameClaimVictoryHeaders reads the headers BotGameClaimVictory declares out of the captured
// response.
func (m *ResponseMeta) BotGameClaimVictoryHeaders() BotGameClaimVictoryHeaders {
	return BotGameClaimVictoryHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BotGameClaimDrawHeaders holds the headers BotGameClaimDraw declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BotGameClaimDrawHeaders struct {
	AccessControlAllowOrigin string
}

// BotGameClaimDrawHeaders reads the headers BotGameClaimDraw declares out of the captured
// response.
func (m *ResponseMeta) BotGameClaimDrawHeaders() BotGameClaimDrawHeaders {
	return BotGameClaimDrawHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// ChallengeListHeaders holds the headers ChallengeList declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ChallengeListHeaders struct {
	AccessControlAllowOrigin string
}

// ChallengeListHeaders reads the headers ChallengeList declares out of the captured
// response.
func (m *ResponseMeta) ChallengeListHeaders() ChallengeListHeaders {
	return ChallengeListHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// ChallengeCreateHeaders holds the headers ChallengeCreate declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ChallengeCreateHeaders struct {
	AccessControlAllowOrigin string
}

// ChallengeCreateHeaders reads the headers ChallengeCreate declares out of the captured
// response.
func (m *ResponseMeta) ChallengeCreateHeaders() ChallengeCreateHeaders {
	return ChallengeCreateHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// ChallengeShowHeaders holds the headers ChallengeShow declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ChallengeShowHeaders struct {
	AccessControlAllowOrigin string
}

// ChallengeShowHeaders reads the headers ChallengeShow declares out of the captured
// response.
func (m *ResponseMeta) ChallengeShowHeaders() ChallengeShowHeaders {
	return ChallengeShowHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// ChallengeAcceptHeaders holds the headers ChallengeAccept declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ChallengeAcceptHeaders struct {
	AccessControlAllowOrigin string
}

// ChallengeAcceptHeaders reads the headers ChallengeAccept declares out of the captured
// response.
func (m *ResponseMeta) ChallengeAcceptHeaders() ChallengeAcceptHeaders {
	return ChallengeAcceptHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// ChallengeDeclineHeaders holds the headers ChallengeDecline declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ChallengeDeclineHeaders struct {
	AccessControlAllowOrigin string
}

// ChallengeDeclineHeaders reads the headers ChallengeDecline declares out of the captured
// response.
func (m *ResponseMeta) ChallengeDeclineHeaders() ChallengeDeclineHeaders {
	return ChallengeDeclineHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// ChallengeCancelHeaders holds the headers ChallengeCancel declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ChallengeCancelHeaders struct {
	AccessControlAllowOrigin string
}

// ChallengeCancelHeaders reads the headers ChallengeCancel declares out of the captured
// response.
func (m *ResponseMeta) ChallengeCancelHeaders() ChallengeCancelHeaders {
	return ChallengeCancelHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// ChallengeAiHeaders holds the headers ChallengeAi declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ChallengeAiHeaders struct {
	AccessControlAllowOrigin string
}

// ChallengeAiHeaders reads the headers ChallengeAi declares out of the captured
// response.
func (m *ResponseMeta) ChallengeAiHeaders() ChallengeAiHeaders {
	return ChallengeAiHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// ChallengeOpenHeaders holds the headers ChallengeOpen declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ChallengeOpenHeaders struct {
	AccessControlAllowOrigin string
}

// ChallengeOpenHeaders reads the headers ChallengeOpen declares out of the captured
// response.
func (m *ResponseMeta) ChallengeOpenHeaders() ChallengeOpenHeaders {
	return ChallengeOpenHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// ChallengeStartClocksHeaders holds the headers ChallengeStartClocks declares. A header the spec
// types as something other than a string is nil when the response omits it.
type ChallengeStartClocksHeaders struct {
	AccessControlAllowOrigin string
}

// ChallengeStartClocksHeaders reads the headers ChallengeStartClocks declares out of the captured
// response.
func (m *ResponseMeta) ChallengeStartClocksHeaders() ChallengeStartClocksHeaders {
	return ChallengeStartClocksHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BulkPairingListHeaders holds the headers BulkPairingList declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BulkPairingListHeaders struct {
	AccessControlAllowOrigin string
}

// BulkPairingListHeaders reads the headers BulkPairingList declares out of the captured
// response.
func (m *ResponseMeta) BulkPairingListHeaders() BulkPairingListHeaders {
	return BulkPairingListHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BulkPairingCreateHeaders holds the headers BulkPairingCreate declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BulkPairingCreateHeaders struct {
	AccessControlAllowOrigin string
}

// BulkPairingCreateHeaders reads the headers BulkPairingCreate declares out of the captured
// response.
func (m *ResponseMeta) BulkPairingCreateHeaders() BulkPairingCreateHeaders {
	return BulkPairingCreateHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BulkPairingStartClocksHeaders holds the headers BulkPairingStartClocks declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BulkPairingStartClocksHeaders struct {
	AccessControlAllowOrigin string
}

// BulkPairingStartClocksHeaders reads the headers BulkPairingStartClocks declares out of the captured
// response.
func (m *ResponseMeta) BulkPairingStartClocksHeaders() BulkPairingStartClocksHeaders {
	return BulkPairingStartClocksHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BulkPairingGetHeaders holds the headers BulkPairingGet declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BulkPairingGetHeaders struct {
	AccessControlAllowOrigin string
}

// BulkPairingGetHeaders reads the headers BulkPairingGet declares out of the captured
// response.
func (m *ResponseMeta) BulkPairingGetHeaders() BulkPairingGetHeaders {
	return BulkPairingGetHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BulkPairingDeleteHeaders holds the headers BulkPairingDelete declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BulkPairingDeleteHeaders struct {
	AccessControlAllowOrigin string
}

// BulkPairingDeleteHeaders reads the headers BulkPairingDelete declares out of the captured
// response.
func (m *ResponseMeta) BulkPairingDeleteHeaders() BulkPairingDeleteHeaders {
	return BulkPairingDeleteHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// BulkPairingIDGamesGetHeaders holds the headers BulkPairingIDGamesGet declares. A header the spec
// types as something other than a string is nil when the response omits it.
type BulkPairingIDGamesGetHeaders struct {
	AccessControlAllowOrigin string
}

// BulkPairingIDGamesGetHeaders reads the headers BulkPairingIDGamesGet declares out of the captured
// response.
func (m *ResponseMeta) BulkPairingIDGamesGetHeaders() BulkPairingIDGamesGetHeaders {
	return BulkPairingIDGamesGetHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// RoundAddTimeHeaders holds the headers RoundAddTime declares. A header the spec
// types as something other than a string is nil when the response omits it.
type RoundAddTimeHeaders struct {
	AccessControlAllowOrigin string
}

// RoundAddTimeHeaders reads the headers RoundAddTime declares out of the captured
// response.
func (m *ResponseMeta) RoundAddTimeHeaders() RoundAddTimeHeaders {
	return RoundAddTimeHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// AdminChallengeTokensHeaders holds the headers AdminChallengeTokens declares. A header the spec
// types as something other than a string is nil when the response omits it.
type AdminChallengeTokensHeaders struct {
	AccessControlAllowOrigin string
}

// AdminChallengeTokensHeaders reads the headers AdminChallengeTokens declares out of the captured
// response.
func (m *ResponseMeta) AdminChallengeTokensHeaders() AdminChallengeTokensHeaders {
	return AdminChallengeTokensHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APICloudEvalHeaders holds the headers APICloudEval declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APICloudEvalHeaders struct {
	AccessControlAllowOrigin string
}

// APICloudEvalHeaders reads the headers APICloudEval declares out of the captured
// response.
func (m *ResponseMeta) APICloudEvalHeaders() APICloudEvalHeaders {
	return APICloudEvalHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIExternalEngineListHeaders holds the headers APIExternalEngineList declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIExternalEngineListHeaders struct {
	AccessControlAllowOrigin string
}

// APIExternalEngineListHeaders reads the headers APIExternalEngineList declares out of the captured
// response.
func (m *ResponseMeta) APIExternalEngineListHeaders() APIExternalEngineListHeaders {
	return APIExternalEngineListHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIExternalEngineCreateHeaders holds the headers APIExternalEngineCreate declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIExternalEngineCreateHeaders struct {
	AccessControlAllowOrigin string
}

// APIExternalEngineCreateHeaders reads the headers APIExternalEngineCreate declares out of the captured
// response.
func (m *ResponseMeta) APIExternalEngineCreateHeaders() APIExternalEngineCreateHeaders {
	return APIExternalEngineCreateHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIExternalEngineGetHeaders holds the headers APIExternalEngineGet declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIExternalEngineGetHeaders struct {
	AccessControlAllowOrigin string
}

// APIExternalEngineGetHeaders reads the headers APIExternalEngineGet declares out of the captured
// response.
func (m *ResponseMeta) APIExternalEngineGetHeaders() APIExternalEngineGetHeaders {
	return APIExternalEngineGetHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIExternalEnginePutHeaders holds the headers APIExternalEnginePut declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIExternalEnginePutHeaders struct {
	AccessControlAllowOrigin string
}

// APIExternalEnginePutHeaders reads the headers APIExternalEnginePut declares out of the captured
// response.
func (m *ResponseMeta) APIExternalEnginePutHeaders() APIExternalEnginePutHeaders {
	return APIExternalEnginePutHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIExternalEngineAnalyseHeaders holds the headers APIExternalEngineAnalyse declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIExternalEngineAnalyseHeaders struct {
	AccessControlAllowOrigin string
}

// APIExternalEngineAnalyseHeaders reads the headers APIExternalEngineAnalyse declares out of the captured
// response.
func (m *ResponseMeta) APIExternalEngineAnalyseHeaders() APIExternalEngineAnalyseHeaders {
	return APIExternalEngineAnalyseHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIExternalEngineAcquireHeaders holds the headers APIExternalEngineAcquire declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIExternalEngineAcquireHeaders struct {
	AccessControlAllowOrigin string
}

// APIExternalEngineAcquireHeaders reads the headers APIExternalEngineAcquire declares out of the captured
// response.
func (m *ResponseMeta) APIExternalEngineAcquireHeaders() APIExternalEngineAcquireHeaders {
	return APIExternalEngineAcquireHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APIExternalEngineSubmitHeaders holds the headers APIExternalEngineSubmit declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APIExternalEngineSubmitHeaders struct {
	AccessControlAllowOrigin string
}

// APIExternalEngineSubmitHeaders reads the headers APIExternalEngineSubmit declares out of the captured
// response.
func (m *ResponseMeta) APIExternalEngineSubmitHeaders() APIExternalEngineSubmitHeaders {
	return APIExternalEngineSubmitHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APITokenHeaders holds the headers APIToken declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APITokenHeaders struct {
	AccessControlAllowOrigin string
}

// APITokenHeaders reads the headers APIToken declares out of the captured
// response.
func (m *ResponseMeta) APITokenHeaders() APITokenHeaders {
	return APITokenHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// APITokenDeleteHeaders holds the headers APITokenDelete declares. A header the spec
// types as something other than a string is nil when the response omits it.
type APITokenDeleteHeaders struct {
	AccessControlAllowOrigin string
}

// APITokenDeleteHeaders reads the headers APITokenDelete declares out of the captured
// response.
func (m *ResponseMeta) APITokenDeleteHeaders() APITokenDeleteHeaders {
	return APITokenDeleteHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// OpeningExplorerMasterHeaders holds the headers OpeningExplorerMaster declares. A header the spec
// types as something other than a string is nil when the response omits it.
type OpeningExplorerMasterHeaders struct {
	AccessControlAllowOrigin string
}

// OpeningExplorerMasterHeaders reads the headers OpeningExplorerMaster declares out of the captured
// response.
func (m *ResponseMeta) OpeningExplorerMasterHeaders() OpeningExplorerMasterHeaders {
	return OpeningExplorerMasterHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// OpeningExplorerLichessHeaders holds the headers OpeningExplorerLichess declares. A header the spec
// types as something other than a string is nil when the response omits it.
type OpeningExplorerLichessHeaders struct {
	AccessControlAllowOrigin string
}

// OpeningExplorerLichessHeaders reads the headers OpeningExplorerLichess declares out of the captured
// response.
func (m *ResponseMeta) OpeningExplorerLichessHeaders() OpeningExplorerLichessHeaders {
	return OpeningExplorerLichessHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// OpeningExplorerPlayerHeaders holds the headers OpeningExplorerPlayer declares. A header the spec
// types as something other than a string is nil when the response omits it.
type OpeningExplorerPlayerHeaders struct {
	AccessControlAllowOrigin string
}

// OpeningExplorerPlayerHeaders reads the headers OpeningExplorerPlayer declares out of the captured
// response.
func (m *ResponseMeta) OpeningExplorerPlayerHeaders() OpeningExplorerPlayerHeaders {
	return OpeningExplorerPlayerHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// OpeningExplorerMasterGameHeaders holds the headers OpeningExplorerMasterGame declares. A header the spec
// types as something other than a string is nil when the response omits it.
type OpeningExplorerMasterGameHeaders struct {
	AccessControlAllowOrigin string
}

// OpeningExplorerMasterGameHeaders reads the headers OpeningExplorerMasterGame declares out of the captured
// response.
func (m *ResponseMeta) OpeningExplorerMasterGameHeaders() OpeningExplorerMasterGameHeaders {
	return OpeningExplorerMasterGameHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TablebaseStandardHeaders holds the headers TablebaseStandard declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TablebaseStandardHeaders struct {
	AccessControlAllowOrigin string
}

// TablebaseStandardHeaders reads the headers TablebaseStandard declares out of the captured
// response.
func (m *ResponseMeta) TablebaseStandardHeaders() TablebaseStandardHeaders {
	return TablebaseStandardHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// TablebaseAtomicHeaders holds the headers TablebaseAtomic declares. A header the spec
// types as something other than a string is nil when the response omits it.
type TablebaseAtomicHeaders struct {
	AccessControlAllowOrigin string
}

// TablebaseAtomicHeaders reads the headers TablebaseAtomic declares out of the captured
// response.
func (m *ResponseMeta) TablebaseAtomicHeaders() TablebaseAtomicHeaders {
	return TablebaseAtomicHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}

// AntichessAtomicHeaders holds the headers AntichessAtomic declares. A header the spec
// types as something other than a string is nil when the response omits it.
type AntichessAtomicHeaders struct {
	AccessControlAllowOrigin string
}

// AntichessAtomicHeaders reads the headers AntichessAtomic declares out of the captured
// response.
func (m *ResponseMeta) AntichessAtomicHeaders() AntichessAtomicHeaders {
	return AntichessAtomicHeaders{
		AccessControlAllowOrigin: m.Header.Get("Access-Control-Allow-Origin"),
	}
}
