// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package item

// Extra game rules separated by commas.Example: `noAbort,noRematch`
type ChallengePostRequestBody_rules int

const (
	NOABORT_CHALLENGEPOSTREQUESTBODY_RULES ChallengePostRequestBody_rules = iota
	NOREMATCH_CHALLENGEPOSTREQUESTBODY_RULES
	NOGIVETIME_CHALLENGEPOSTREQUESTBODY_RULES
	NOCLAIMWIN_CHALLENGEPOSTREQUESTBODY_RULES
	NOEARLYDRAW_CHALLENGEPOSTREQUESTBODY_RULES
)

func (i ChallengePostRequestBody_rules) String() string {
	return []string{"noAbort", "noRematch", "noGiveTime", "noClaimWin", "noEarlyDraw"}[i]
}

func ParseChallengePostRequestBody_rules(v string) (any, error) {
	result := NOABORT_CHALLENGEPOSTREQUESTBODY_RULES
	switch v {
	case "noAbort":
		result = NOABORT_CHALLENGEPOSTREQUESTBODY_RULES
	case "noRematch":
		result = NOREMATCH_CHALLENGEPOSTREQUESTBODY_RULES
	case "noGiveTime":
		result = NOGIVETIME_CHALLENGEPOSTREQUESTBODY_RULES
	case "noClaimWin":
		result = NOCLAIMWIN_CHALLENGEPOSTREQUESTBODY_RULES
	case "noEarlyDraw":
		result = NOEARLYDRAW_CHALLENGEPOSTREQUESTBODY_RULES
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeChallengePostRequestBody_rules(values []ChallengePostRequestBody_rules) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i ChallengePostRequestBody_rules) isMultiValue() bool {
	return false
}
